src/status_im/models/pending_messages.cljs
src/status_im/protocol/ack.cljs
src/status_im/protocol/handlers.cljs

1) Usage of :ack-of-message instead of :message-id 
2) Prevent update of message's status if it was already set to `:seen`.
fixes #248

Delivery status issues #248

---

.re-natal
package.json
src/status_im/accounts/handlers.cljs
src/status_im/accounts/screen.cljs
src/status_im/android/platform.cljs
src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/wallet_chat.cljs
src/status_im/chat/screen.cljs
src/status_im/chat/sign_up.cljs
src/status_im/chat/utils.cljs
src/status_im/commands/handlers/jail.cljs
src/status_im/commands/handlers/loading.cljs
src/status_im/components/chat_icon/screen.cljs
src/status_im/components/styles.cljs
src/status_im/components/text_field/styles.cljs
src/status_im/components/text_field/view.cljs
src/status_im/constants.cljs
src/status_im/contacts/styles.cljs
src/status_im/db.cljs
src/status_im/handlers.cljs
src/status_im/ios/platform.cljs
src/status_im/profile/screen.cljs
src/status_im/profile/styles.cljs
src/status_im/profile/validations.cljs
src/status_im/translations/en.cljs

I've added spec validations to profile — now it is impossible to use names like "wallet" and "console", there is also a check for validity of email.
This task also includes small fixes for `status-im.components.text-field.view`: it now sets and uses `default-value` instead of just `value` and don't re-render the component each time we change its text.

Profile validations (#235)

---

src/status_im/chat/screen.cljs
src/status_im/chat/styles/screen.cljs
src/status_im/chat/views/toolbar_content.cljs
src/status_im/chats_list/screen.cljs
src/status_im/components/refreshable_text/view.cljs
src/status_im/components/sync_state/gradient.cljs
src/status_im/components/sync_state/offline.cljs
src/status_im/components/sync_state/styles.cljs
src/status_im/components/toolbar/styles.cljs
src/status_im/components/toolbar/view.cljs
src/status_im/constants.cljs
src/status_im/db.cljs
src/status_im/handlers.cljs
src/status_im/protocol/handlers.cljs
src/status_im/translations/en.cljs

It may seem a bit overcomplicated, but it isn't :)
The main and most important part of it is `:initialize-sync-listener` handler in `status-im.protocol.handlers` namespace. Here we add a listener that switches states when a new portion of information comes (the main purpose of all this "overcomplication" is to make animations look smooth and also to avoid flickering when the information comes too fast).
The easiest way to test it without this listener is by executing the combination of commands manually, like that:
```
(js/setTimeout #(dispatch [:set :sync-state :pending]) 1500)
(js/setTimeout #(dispatch [:set :sync-state :offline]) 6000)
(js/setTimeout #(dispatch [:set :sync-state :pending]) 9500)
(js/setTimeout #(dispatch [:set :sync-state :synced]) 12500)
```

Sync indicator (#312)

---

android/app/src/main/AndroidManifest.xml
resources/console.js
src/status_im/android/core.cljs
src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/console.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/views/message.cljs
src/status_im/commands/handlers/jail.cljs
src/status_im/components/react.cljs
src/status_im/components/sync_state/offline.cljs
src/status_im/handlers.cljs
src/status_im/handlers/server.cljs
src/status_im/network/handlers.cljs
src/status_im/network/net_info.cljs
src/status_im/protocol/handlers.cljs
src/status_im/utils/scheduler.cljs
src/status_im/utils/utils.cljs
test/cljs/status_im/test/handlers_stubs.cljs

fixes #226
When user is not connected to wifi/mobile network/etc he will see `offline` bage (the same as when there are errors at syncing):
When some troubles appear at sending phone number or confirmation code to the server user will see toast with error and the message will be not sent, so the user will be able to try again. 
Maybe there is a better way to show errors there but I'm not sure how.

Show connectivity issues & displaying errors in console chat (#226)

---

src/status_im/protocol/web3/delivery.cljs

Fixes #381
The problem happens because of one small bug in `reset-pending-messages!` function — when there is no key, it resets `messages` map to `nil` value

Fix for red screen on login (#381)

---

src/status_im/chat/styles/message.cljs
src/status_im/chat/views/request_message.cljs

Fixes #400
It is a general improvement — if a text is too small in height, we display the request icon in the center of text block, thus getting rid of this bug.

Request icon in message is overlapped by the next message fix (#400)

---

resources/commands.js
src/status_im/accounts/login/handlers.cljs
src/status_im/chat/handlers/commands.cljs
src/status_im/chat/handlers/webview_bridge.cljs
src/status_im/contacts/handlers.cljs
src/status_im/contacts/subs.cljs
src/status_im/transactions/handlers.cljs

fixes #430
1. Validation of `to` address was added to `!send` command:
2. If there is no address in contact entry it is not shown in the list when user select contact to send ETH (this will not have too much sense when we will derive address from public key, but it has some sense now)

Prevent !send with null "to" address

---

src/status_im/chat/screen.cljs
src/status_im/utils/views.clj

```clojure
;; before
(defn v [params]
(let [s "some_string"
a (subscribe [:a])
b (subscribe [:b s])
c (atom nil)
d (reagent.core/atom nil)]
(reagent.core/create-class
{:component-did-mount (fn [] (+ @a @c))
:reagent-render      (fn [params]
@b
[view [text (str s @d)]])})))
;; after
(defview v [params]
[s "some_string"
a [:a] 
;; bindings above can be used
b [:b s]
;; clojure.core/atom and reagent.core/atom will be automatically
;; dereferenced by defview
c (atom nil)
d (reagent.core/atom nil)]
;; component's map can be passed as third parameter
{:component-did-mount (fn [] (+ a c))}
[view [text (str s d)]])
```

Extended defview macro

---

src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/receive_message.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/screen.cljs
src/status_im/chat/subs.cljs
src/status_im/data_store/chats.cljs
src/status_im/data_store/messages.cljs
src/status_im/data_store/realm/messages.cljs
src/status_im/data_store/realm/schemas/account/v1/chat.cljs
src/status_im/data_store/realm/schemas/account/v1/message.cljs
src/status_im/protocol/chat.cljs
src/status_im/protocol/core.cljs
src/status_im/protocol/handlers.cljs

Fixes #550.
:clock-value now works better and there should be no problems with message order. I've checked it — everything works fine.

Order of messages fix (#550)

---

src/status_im/chat/handlers.cljs
src/status_im/protocol/handlers.cljs

Fixes #570.
This problem reproduces because of the unnecessary double `dispatch`. The message simply arrived before we saved the new chat to the database. By removing the `dispatch` we guarantee that the incoming message will always use the updated value of chat object.
It was harder to find this bug than to fix it.

Fix for "Add to contacts" request (#570)

---

src/status_im/chat/views/message_input.cljs

As a user, I would expect the keyboard to automatically switch to uppercase for the first letter of a sentence.
This change enables that, using the _autoCapitalize_ property for [TextInput](https://facebook.github.io/react-native/docs/textinput.html).

chat: auto capitalize first letter of each sentence

---

resources/commands.js

Quick fix to prevent non-numbers in request command. Used the same check as the send command (web3.toWei).
Also preventing 0 or negative amount, as I believe makes no sense (I was able to "send -3 ether", but the app crashed when it tried to confirm the transaction).
fixes #668

Prevent non-positive-number amounts for send / request commands (#668)

---

src/status_im/chat/suggestions.cljs

Regex needed to be updated in order to accommodate the move from the "!" command char to the "/" command char.
chat-consts/command-char should not be a character that cannot be used in a regex, after "^"

chat.suggestions: updated regex for switch from ! to / command char

---

src/status_im/chat/views/message.cljs
src/status_im/components/share.cljs
src/status_im/handlers.cljs
src/status_im/profile/handlers.cljs
src/status_im/profile/screen.cljs

Overview: reused the same function from the profile screen (which copies the public key)
- I've made it work only on the text messages, not command ones
- It's copying the raw content, so text decoration is preserved. Maybe for the future, another option could be added to copy just the text?
**Implementation:**
Both the share function and the event handler were in the _profile_ namespace, although they seemed more general to me.
- Moved the share function to the existent component/share namespace.
- Moved the share event handler to the root handlers file (couldn't figure out a better place)
- Added the share action to the message component (not sure if I choose the best place) and cleared namespace declarations everywhere.
fixes #639

Add ability to copy/paste messages #639

---

src/status_im/components/toolbar/view.cljs

Search input on Discover can leave header in indeterminate state (#695)

---

modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
modules/react-native-status/ios/RCTStatus/RCTStatus.m
src/status_im/accounts/login/handlers.cljs
src/status_im/components/status.cljs

Fixes #688
Works on Android (devices + emulator) and real iOS devices.
It doesn't work in iOS Simulator, and seems like I've found the reason why:
_WebView cookies are stored by the device's operating system.  The location will vary by OS and I'm pretty sure it's opaque to apps._
_... webView:deleteCookies() not working on OS X.  Unfortunately, OS X shares cookies between all webview instances (including Safari) so enabling CoronaSDK apps to delete all of them would have surprising side-effects._
(from here: https://forums.coronalabs.com/topic/9540-delete-cookies-from-webview/)

Cleaning WebView sessions (#688)

---

src/status_im/accounts/handlers.cljs
src/status_im/accounts/screen.cljs
src/status_im/accounts/views/account.cljs

The reason of this bug
```
; add accounts screen to history ( maybe there is a better way ? )
(dispatch [:navigate-to-clean :accounts])
```
should be a better way, I think better to add :accounts key into the :navigation-stack at the app initialization, but i don't know app's structure well, so, it needs to be refactored i think
fixes #675

Back button doesn't work on recover screen Bug/#675

---

resources/commands.js

#665
Since all countries use either comma or point as a decimal mark (https://en.wikipedia.org/wiki/Decimal_mark), simple `replace` works great here.

Alternate Currency Formats breaks ability to send ETH (#665)

---

src/status_im/components/drawer/view.cljs
src/status_im/profile/validations.cljs

Fixes #685 
I mainly added a couple of rules to the profile name spec, and made sure that the drawer input was using that for validation as well. 
The UI still remains a bit strange, as the user can input an invalid name, and it will show in a red color (or empty), but it won't save, without warning.

components, profile: better username validation #685

---

resources/console.js
src/status_im/chat/handlers/send_message.cljs

This PR fixes #684 and the scariest Instabug crash (https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/crashes/25).
This bug happens because of our `str-to-map` and `map-to-str` functions (https://github.com/status-im/status-react/blob/develop/src/status_im/data_store/messages.cljs#L11). Since we split the char sequence by semicolon (;) and equals sign (=), we can't use these chars in the input. The easiest solution is to use other characters in this sequence, but
1) it will ruin the existing messages, and users will see crap instead of previews;
2) all characters can be used inside a password, so by replacing ";" and "=" with something else, we postpone the problem instead of solving it.
In this PR I simply remove `password` and `password-confirmation` …

Semicolon in password works fine now (#684); fix for crash #25

---

src/status_im/chat/screen.cljs

bug/emoji-can-persist-after-chat-closed-#647 

---

.re-natal
android/app/build.gradle
android/app/src/main/java/im/status/ethereum/MainApplication.java
android/settings.gradle
externs/externs.js
package.json
src/status_im/chat/handlers/webview_bridge.cljs
src/status_im/components/drawer/view.cljs
src/status_im/components/nfc.cljs

There are 3 methods in `nfc-react-native` package. This PR allows to use any of them in DApps.
**JS API**
```javascript
// getCardId
statusAPI.dispatch(
"nfc", 
{
data: {
event: "get-card-id"
}, 
callback: function (params) {
// params.card, params.error
}
}
);
// readTag
statusAPI.dispatch(
"nfc", 
{
data: {
event: "read-tag",
params: {
sectors: [{ sector: 5, bloques: [1,2], clave: 'FFFFFFFFFFFF', tipoClave: 'A' }]
}
}, 
callback: function (params) {
// params.card, params.error
}
}
);
// writeTag
statusAPI.dispatch(
"nfc", 
{
data: {
event: "write-tag",
params: {
sectors: [{ sector: 5, bloques: [ ... ] }],
id: "CARD_ID_GOES_HERE"
}
}, 
callback: function (params) {
// params.card, params.error
}
}
);
```
Fixes #670

NFC access for DApps (#670)

---

src/status_im/profile/handlers.cljs
src/status_im/profile/screen.cljs

Since phone change requires sms verification, we don't want user let to edit it directly on profile page.
Instead, we redirect him to the Console automatically issuing :phone command.

fix #701: Redirect user to the console when he tries to edit phone number on profile page

---

resources/commands.js
resources/status.js
resources/wallet.js
src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/commands.cljs
src/status_im/chat/handlers/console.cljs
src/status_im/chat/handlers/receive_message.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/views/message.cljs
src/status_im/chat/views/request_message.cljs
src/status_im/chats_list/views/inner_item.cljs
src/status_im/commands/handlers/jail.cljs
src/status_im/components/status.cljs
src/status_im/data_store/messages.cljs
src/status_im/i18n.cljs
src/status_im/protocol/handlers.cljs
src/status_im/transactions/screen.cljs
src/status_im/transactions/views/transaction_page.cljs
src/status_im/translations/en.cljs

In order to fix #645 we needed to change the way we do rendering, because it is almost impossible to translate the content that was pre-rendered before and saved to database. 
This PR introduces the new way of rendering — I've removed `:preview` and `:rendered-preview` from the message model and made the process dynamic. And since the rendering became dynamic, we can easily translate almost everything every time we need.
Fixes #645, #754

Generating message preview on the fly (#645, #754)

---

src/status_im/i18n.cljs

Fixes #783 
This bug happened because iOS uses delimiters (`1 000 000.12`) while Android doesn't (`1000000.12`)

Wrong formatting of ETH value at transactions screen on Android (#783)

---

resources/default_contacts.json
resources/state_of_the_dapps.json
src/status_im/commands/handlers/loading.cljs
src/status_im/contacts/screen.cljs
src/status_im/contacts/subs.cljs
src/status_im/translations/en.cljs
src/status_im/utils/js_resources.cljs

This PR solves #599 
Changes:
1. Moved the 3 state-of-the-dapps  from `default_contact.json` to `state_of_the_dapps.json` and added `utils/js-resources`
2. `commands/handlers/loading.cljs`: in `:load-default-contacts!` handler - load both `js-res/default-contacts` and  `js-res/state-of-the-dapps`
3. `contacts/screen.cljs`: Create a new "State of the Dapps" group in the contacts screen
4. `contacts/subs.cljs`: `register-sub` for state-of-the-dapps data + fix the filter for `:all-added-people` to exclude also `state-of-the-dapp?`
5. `translations/en.cljs`: added a string for `:contacts-group-state-of-the-dapps`
Questions:
A. Some names and urls returned by state-of-the-dapps are a bit different that the ones we had in `default_contact.json`:
1. "Flight Delay Insurance" instead of "Flight …

contacts: create "State of the Dapps" group

---

src/status_im/components/drawer/view.cljs
src/status_im/components/text_field/view.cljs
src/status_im/profile/screen.cljs
src/status_im/profile/validations.cljs

Fixes #774 
The cause and solution used can be found in this RN issue: https://github.com/facebook/react-native/issues/7047
Besides fixing the issues explicit in #774, the following issues are also solved in this PR:
- Editing the username (on drawer or profile screen) and switching account showed the first account's username in the drawer.
- Editing the username (on drawer or profile screen) and leaving it in a invalid state didn't save the invalid username (which is correct), but didn't reverse it either (so you could navigate around and even switch accounts but the invalid username would persist on the drawer). Now:
- On the drawer, when the user finishes editing the username, the input reverses to the previous saved one if the new one is invalid.
- On the profile screen, if the user …

Fix profile and drawer input inconsistencies (#774)

---

src/status_im/chat/subs.cljs
src/status_im/chat/views/response.cljs

Fixes #772
It seems like there is no need for `:input-margin` to be that difficult.

Magic suggestions area (#772)

---

src/status_im/chat/handlers/commands.cljs
src/status_im/chat/views/message_input.cljs
src/status_im/chat/views/new_message.cljs
src/status_im/chat/views/response.cljs
src/status_im/commands/handlers/jail.cljs

Fixes #776
Also fixes bugs with /browse command on Android

Persist keyboard when typing command and moving to parameters (#776)

---

src/status_im/chat/screen.cljs

Additional fix for https://github.com/status-im/status-react/issues/772#issuecomment-279994295
Now it is impossible for suggestions to be opened when no command is selected.

Magic suggestions fix (#772)

---

src/status_im/chat/handlers/commands.cljs
src/status_im/chat/views/message_input.cljs

The problem appeared after fixing autofocus for command input. When user chooses command, cursor sets at the beginning of the input (before “с “) and when user types something (like sets ETH value for `/send` command) he changes command prefix and this closes command.
Before:
After:
status: ready

fix cursor position for command input

---

package.json
postinstall.sh

The newest version of `status-dev-cli` should be installed globally, so there is no need to include it to the main application.

status-dev-cli removed

---

src/status_im/data_store/realm/core.cljs

Fixes problem with transforming of Realm objects/collections to plain JS objects in Chrome debug session by extending them with IEncodeClojure protocol.
- shake phone
- start JS remote debugging
status: ready

Add ability to debug application in Chrome

---

resources/commands.js

fixes #874 
The error appeared on iOS and Android, Status 0.9.3.
`resources/command.js` defines JavaScript `send` and `receive` functions, which are loaded up into the re-frame database by `commands/handlers/loading.cljs`. `send()`'s validator calls `replace()` on the amount, but `receive()` did not. The fix simply calls `replace()` on `receive()` as well, so its validator acts like `send`'s validator.
Note that this now applies to all languages, not just German: any language-user can type in "0,5" without error, just like any language-user …

resources, commands.js, replace() comma to period

---

src/status_im/android/core.cljs
src/status_im/android/platform.cljs
src/status_im/chats_list/screen.cljs
src/status_im/ios/core.cljs
src/status_im/ios/platform.cljs
src/status_im/new_chat/screen.cljs
src/status_im/new_chat/styles.cljs
src/status_im/translations/en.cljs

UI Changes for the "Start new chat" screen:
- Android now also have the list with the 3 options in the screen (replaces the 3 options in the chat list action button, this was done in another PR).
- New/changed colors, elements, positioning, etc.
- Updated the toolbar
- Go to chat list screen
- Tap the action button
- Tap new chat option
- Go to chat list screen
- Tap the **+** button in the toolbar.
status: done

"Start new chat" screen UI refresh

---

src/status_im/android/platform.cljs
src/status_im/components/context_menu.cljs
src/status_im/components/list_selection.cljs
src/status_im/ios/platform.cljs

fixes #920 
The share dialog was broken everywhere in iOS, not just in chat messages. It is fixed now.
I moved back the cancel button code from `context-menu` to iOS `show-action-sheet`, so that all iOS menus have the cancel button automatically.
status: ready

Bug: share dialog crash #920

---

src/status_im/components/react.cljs
src/status_im/new_group/screen_private.cljs
src/status_im/new_group/views/chat_group_settings.cljs
src/status_im/new_group/views/contact_toggle_list.cljs
src/status_im/profile/edit/screen.cljs

fixes #924 
Save button now shows correctly above the virtual keyboard when it pops up, in all screens containing it:
- Create group chat
- Group chat settings
- Add contact to group chat
- Create contact group
- Edit contact group
- Edit profile
status: ready

Bug: save button behind keyboard in iOS #924

---

src/status_im/android/platform.cljs
src/status_im/contacts/styles.cljs
src/status_im/ios/platform.cljs
src/status_im/new_group/styles.cljs

fixes #923 
- Fixes styles when the contact group name is too long.
- Edit button now appears correctly.
- Also fixed same issues in Reorder Groups screen.
Fixed and tested in Android and iOS
status: ready

Bug: contact group's long title style #923

---

src/status_im/android/platform.cljs
src/status_im/chat/screen.cljs
src/status_im/chat/styles/datemark.cljs
src/status_im/chat/styles/message.cljs
src/status_im/chat/styles/screen.cljs
src/status_im/chat/subs.cljs
src/status_im/chat/views/message.cljs
src/status_im/chat/views/request_message.cljs
src/status_im/chat/views/toolbar_content.cljs
src/status_im/components/styles.cljs
src/status_im/contacts/subs.cljs
src/status_im/ios/platform.cljs
src/status_im/translations/en.cljs

- 1-on-1 chats now visually similar to group chats: sender's icon besides messages
- Sender's name in each message
- Datemark styles
- Confirmation status only in last outgoing message
- Small style tweaks everywhere
I didn't rework the commands' messages (location, request, etc), only made small tweaks to make them fit together with the other changes. I think it will make more sense to rework these together with the commands themselves.
status: ready

Chat messages UI refresh

---

src/status_im/translations/de.cljs
src/status_im/translations/en.cljs
src/status_im/translations/es.cljs
src/status_im/utils/datetime.cljs

Added a datetime-ago-format in translations to support different sentence order.
fixes #621 
Default format is "{{number}} {{time-intervals}} {{ago}}" (i.e. "1 minute ago"), but for some locales you can choose different order, for example "{{ago}} {{number}} {{time-intervals}}" for de and es ( "vor 1 Minute", "hace 1 minuto")
- change phone locale to "de"
- Open Status
- check if someone's toolbar status says something like "vor 1 Minute"
- change locale to "en"
- Open Status
- check if someone's toolbar status says something like  "1 minute …

added a datetime-ago-format 

---

bots/console/bot.js
bots/demo_bot/bot.js
bots/mailman/bot.js
resources/default_contacts.json
resources/status.js
src/status_im/bots/handlers.cljs
src/status_im/bots/subs.cljs
src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/commands.cljs
src/status_im/chat/handlers/receive_message.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/subs.cljs
src/status_im/chat/views/response.cljs
src/status_im/commands/handlers/jail.cljs
src/status_im/commands/handlers/loading.cljs
src/status_im/commands/utils.cljs
src/status_im/components/react.cljs
src/status_im/components/status.cljs
src/status_im/data_store/messages.cljs
src/status_im/handlers.cljs
src/status_im/subs.cljs
src/status_im/transactions/handlers.cljs
src/status_im/utils/js_resources.cljs
src/status_im/utils/slurp.clj

PR contains the next features/changes:
1. `status.defineSubscription` method was added to allow a bot to react on changes in `bot-db` and add another calculated value to `bot-db` in the result. Maybe better to call it `defineReaction`
```js
status.defineSubscription(
// the name of subscription and the name of the value in bot-db
// associated with this subscription
"doubledValue",
// the map of values on which subscription depends: keys are arbitrary names
// and values are db paths to another value
{value: ["sliderValue"]},
// the function which will be called as reaction on changes of values above,
// should be pure. Returned result will be associated with subscription in bot-db
doubledValueLabel
);
```
2. `status.component.subscribe(path)` (alternatively just `["subscribe", …

Interactive suggestions

---

src/status_im/transactions/screens/unsigned_transactions.cljs

In the "Unsigned transactions" screen, the X button in the toolbar no longer cancels all pending transactions. Now it just closes the screen.
status: ready

Transactions back button doesn't cancel transactions

---

src/status_im/android/platform.cljs
src/status_im/chat/screen.cljs
src/status_im/chat/styles/animations.cljs
src/status_im/chat/styles/input/input.cljs
src/status_im/chat/styles/screen.cljs
src/status_im/chat/subs.cljs
src/status_im/chat/views/input/animations/expandable.cljs
src/status_im/chat/views/input/parameter_box.cljs
src/status_im/chat/views/input/result_box.cljs
src/status_im/chat/views/input/utils.cljs
src/status_im/ios/platform.cljs

fixes item 5 in #994 
- Expanded the top margin of the draggable box, to be able to drag it down without sliding the OS top bar down. The limit now (max height) is at the middle of the toolbar, which should be always a "safe" tapping area.
- Added a dark overlay beneath the box, over the chat screen below.
- The whole header can now be used to drag the box down.
- Open some Dapps to activate the browse command.
- Try some commands in Console, like /faucet and /debug
The following are not blocking and can be addressed later:
- The overlay should hide when the box is dragged beneath 50%. Also, this should be animated.
- In Android, with the overlay, the status bar color is a bit off. Not straightforward to fix, RN Android status bar has some wierd issues.
status: ready

Bigger result-box/parameter-box top margin

---

.re-natal
env/dev/env/android/main.cljs
src/status_im/android/platform.cljs
src/status_im/chats_list/styles.cljs
src/status_im/components/contact/styles.cljs
src/status_im/contacts/styles.cljs
src/status_im/ios/platform.cljs
src/status_im/profile/screen.cljs
src/status_im/profile/styles.cljs

Fixes #945 
Also removes explicit platform-specific usage from several places.

Style fixes; Emoji in Display name is cut on Chats, View Profile and Contacts (#945)

---

src/status_im/chat/screen.cljs

Hide opened keyboard when user taps on chat (#1057)

---

src/status_im/chat/styles/screen.cljs
src/status_im/components/context_menu.cljs
src/status_im/components/toolbar_new/styles.cljs
src/status_im/components/toolbar_new/view.cljs
src/status_im/transactions/styles/screens.cljs

fixes #1066 
I intended to extend the area by 16x16, as below. However, as the toolbar buttons are 24 apart from each other, the new area is a bit thinner (12x16). 
status: ready

Expanded toolbar buttons' touch area (#1066)

---

resources/commands.js

Fixes #1046
The solution is quite simple — since the smallest unit of ETH is 10^-18 (https://ethereum.stackexchange.com/questions/13811/what-is-the-smallest-amount-of-ether), we can simply remove the additional digits.

Any sum with more than 19 digits after comma is converted to 0 ETH (if /send) (#1046)

---

modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
modules/react-native-status/ios/RCTStatus/RCTStatus.m
src/status_im/components/status.cljs
src/status_im/transactions/handlers.cljs

fixes #1029 
Now `status-go` `completeTransactions` method (which wasn't being used before) is used instead of `completeTransaction`.
I decided to not keep the interface to `completeTransaction`, as it was not used anymore. Nor can I see any reason to use it in the future.
[Here is the address](https://ropsten.etherscan.io/address/0x323a7fd769a0f106d6b41232b10c44064bb4be88) used in the tests, you can now see sets of 2 or more transactions sent in the same time. Tested in Android and iOS.
status: ready

Send multiple transactions fix (#1029)

---

src/status_im/chat/views/input/input.cljs

Emoji and numeric keyboards are shown when tap on /send while emojis are opened (#1056)

---

src/status_im/chats_list/screen.cljs
src/status_im/contacts/screen.cljs

fixes #1097 
The button is now back to its correct position, in the Chat List and Contact List.
status: ready

Fix Android action button position (#1097)

---

package.json
src/status_im/chat/handlers/console.cljs
src/status_im/components/network_info.cljs
src/status_im/translations/en.cljs

Fixes #1101 
I've updated `react-native-network-info` library because the developer of this lib has changed the code that determines the IP. Now everything should be okay in 99.9% of cases.
I've also added a fallback message for the remaining 0.01%. Probably nobody will see this message, but since IP can be `null`, we should handle it.

IP address is not shown for /debug On (#1101)

---

.re-natal
package.json
src/status_im/chat/handlers.cljs
src/status_im/chat/styles/input/input.cljs
src/status_im/chat/views/input/input.cljs
src/status_im/components/react.cljs
src/status_im/data_store/chats.cljs

React Native 0.40+ gave us an ability to fix #676 because the blocking issue (https://github.com/facebook/react-native/issues/6552) has been resolved.
This PR also fixes #1067 by adding an `input-touch-handler` and #1110 by cleaning data on re-login.
All these issues are related to input text, so I decided to create one single PR instead of several ones.

Input fixes (#1067, #676), #1110

---

src/status_im/chat/screen.cljs
src/status_im/chat/views/message/message.cljs

fixes #1143, #1142 
Now long tap in message works with input focused, in both platforms, opening the menu.
Normal tap still works as planned: hide the keyboard in iOS but not in Android.
status: ready

Fix chat long tap not working with input focused (#1143)

---

src/status_im/chats_list/styles.cljs
src/status_im/chats_list/views/inner_item.cljs
src/status_im/components/common/common.cljs
src/status_im/components/common/styles.cljs
src/status_im/components/contact/contact.cljs
src/status_im/components/contact/styles.cljs
src/status_im/components/context_menu.cljs
src/status_im/profile/screen.cljs
src/status_im/profile/styles.cljs

fixes #1072 
Expanded the tap area for the buttons in the chats list, contacts list and profile screen
status: ready

Bigger tap area for buttons (#1072)

---

src/status_im/chat/styles/input/input.cljs
src/status_im/chat/views/input/input.cljs

Fixes #1151  
Also removes redundant `:secure-text-entry` from `seq-input`

Command and argument are misaligned [iOS only] (#1151)

---

src/status_im/chat/views/input/input.cljs

fixes #1111
There is a bug in RN on Android when using multiline text input https://github.com/facebook/react-native/issues/7047 
@annadanchenko I've fixed this issue using most painless way, but text input size doesn't recalculate after press enter, only after input next symbol
@alwx I don't know why but genymotion works different from real device, and you should press "Enter" on your computer's keyboard and in this case, it works same way as on real device
status: …

Bug/Keyboard is hidden on hit Enter instead of moving to new line in input field (#1111)

---

src/status_im/new_group/handlers.cljs

- Open Status
- Click + (start a new chat)
- Create a new public chat
- Navigate back
- user is now redirected to chats list
status: ready

Fixes #1180 Cleanup navigation stack when creating public group

---

modules/react-native-status/android/build.gradle
modules/react-native-status/ios/RCTStatus/pom.xml
package.json
src/status_im/accounts/handlers.cljs
src/status_im/data_store/pending_messages.cljs
src/status_im/data_store/realm/pending_messages.cljs
src/status_im/data_store/realm/schemas/account/v7/contact.cljs
src/status_im/data_store/realm/schemas/account/v7/core.cljs
src/status_im/data_store/realm/schemas/account/v7/pending_message.cljs
src/status_im/protocol/core.cljs
src/status_im/protocol/discoveries.cljs
src/status_im/protocol/group.cljs
src/status_im/protocol/listeners.cljs
src/status_im/protocol/message.cljs
src/status_im/protocol/web3/delivery.cljs
src/status_im/protocol/web3/filtering.cljs
src/status_im/protocol/web3/keys.cljs
src/status_im/protocol/web3/public_group.cljs
src/status_im/protocol/web3/transport.cljs
src/status_im/protocol/web3/utils.cljs

related to https://github.com/status-im/status-go/pull/153
Messaging should work the same way as it worked in `develop`
Older versions of app will not able to communicate with this version

migrate to Geth/1.6.1-unstable

---

package.json

I've updated react-native-network-info because it was a bit buggy, for instance, IP addresses may have looked this way: `fe80::4680:ebff:fea9:95d2%wlan0`.

react-native-network-info update

---

src/status_im/contacts/screen.cljs
src/status_im/new_group/screen_private.cljs
src/status_im/translations/en.cljs
src/status_im/utils/utils.cljs

Added confirmation dialog for the delete actions
- Open Status
- Open contacts
- Edit group
- Delete group
- A confirmation alert will popup
status: ready
NOTE: `:delete-contact-confirmation` and `:delete-group-confirmation` texts should be confirmed

Fixes #919 Confirmation dialog for the delete actions

---

src/status_im/components/list_selection.cljs
src/status_im/profile/screen.cljs

Fixes #1222 
Do not crash when sharing empty text. Hide sharing options when nothing can be shared
- Open Status
- Go to console
- Select profile
- Address should be blank
- Click on '...': no sharing options should be available (Only 'Show QR')
Note I also fixed the original issue (sharing null won't fail anymore).
status: ready

Fixes #1222 Do not crash when sharing null address.

---

src/status_im/components/camera.cljs
src/status_im/components/permissions.cljs
src/status_im/components/react.cljs
src/status_im/translations/en.cljs
src/status_im/utils/fs.cljs

fix #1220 No response if use 'Select from gallery' after access to photos was denied
- Open Status first time
- Open Profile
- Edit Profile
- Edit profile picture
- tap on Select from Gallery. As a result, popup is shown "Deny/Allow" access to photos
- Deny access to photos
- Tap on Select from Gallery again.
- An error message is  shown
status: ready

Fixes #1220 Do not let catch escape

---

.re-natal
android/app/build.gradle
android/app/src/main/java/im/status/ethereum/MainApplication.java
android/settings.gradle
ios/StatusIm.xcodeproj/project.pbxproj
package.json
src/status_im/chat/handlers/console.cljs
src/status_im/components/network_info.cljs
src/status_im/translations/en.cljs

This PR removes `react-native-network-info` and changes the response to `/debug On` command.

No more react-native-network-info, updated /debug command response

---

src/status_im/data_store/realm/core.cljs

fixes #1245 
Updating your profile status with a hashtag and a character that needs to be escaped causes the app to crash. This was caused by the string not being escaped in some cases when sent to realmjs as a query.
This pull request updates the escaped query value via `goog.string.escapedString` instead of the currently used `string/replace`.
I also removed a dead function `get-by-filter` as it's not used anywhere and could also lead to a similar error if the user forgets to escape the filter.
Open Status
Open profile
Edit profile
in Status type #\ and tap Save
status: ready

Bug: Can't set status with #\ (#1245)

---

bots/demo_bot/bot.js
resources/status.js
src/status_im/chat/handlers/send_message.cljs
src/status_im/commands/handlers/jail.cljs
src/status_im/handlers.cljs
src/status_im/utils/js_resources.cljs

`status.sendMessage(text)` - will send message in 1-to-1 chat with bot
`status.showSuggestions(markup)` - allows to add markup to suggestion area
`status.sendMessage/showSuggestions` are signal based so can be called from callbacks (and will be useful when event loop will be added to jail).
Example: https://github.com/status-im/status-react/blob/feature/signal-based-messages-suggestions-in-jail/bots/demo_bot/bot.js#L103
status: ready

status.sendMessage/showSuggestions methods in jail

---

src/status_im/profile/handlers.cljs

Fixes #1355 
Parameter of the previous command is shown if use Send Transaction from a user profile
`fix`: make sure seq arguments are cleared before navigating back to chat 
- Launch app "Status"
- Login with valid credentials
- Go to 1-1 Chats
- Select any command (ex. Location) and type smth in the field
- Tap on the "Profile" icon
- Select "Send"
status: ready

Clear Seq arguments before navigating back to chat. Fixes #1355

---

src/status_im/components/text_field/view.cljs

fixes #1297
In _Join public chat_ screen user types "A" in topic. After this
all other typed characters are not shown at all (on iOS)
next typed character "deletes" the first one so field is empty (on Android)
- Open Status
- Open Chats
- tap on +
- tap Join public chat
- set keyboard to uppercase and type "A"
- type "m". check that topic field contains "m".
status: ready

Do not prevent input if first character is invalid

---

src/status_im/accounts/login/screen.cljs

fixes #1285
Keyboard hides after tap on return instead of logging in on Sign in screen
- Open Status
- Type password on Sign in screen
- On device keyboard tap on "Return" button (if iOS) or Done button (if Android)
- User is signed in
status: ready

Tap on return permits sign-in. Fixes #1285

---

project.clj
src/status_im/chat/handlers/input.cljs
src/status_im/chat/models/input.cljs
src/status_im/chat/subs.cljs
src/status_im/chat/views/input/input.cljs
test/cljs/status_im/test/chat/models/input.cljs
test/cljs/status_im/test/runner.cljs

Fixes #1212
Can't send @browse command if space is typed before url
- Open Status
- Open console
- Type " @browse google.com" (spaces can be added before or after browse)
- URL should be correctly browsed
Also allow command to be recognized if a space is added before `@`. Some unit tests validate various extra spaces pattern.
status: ready

Fixes #1212

---

android/app/src/main/AndroidManifest.xml

fixes #1236 
By adding android:installLocation="auto" to the manifest (https://developer.android.com/guide/topics/manifest/manifest-element.html) , the location the app is installed to is allowed to be changed, so that it can be put on the SD card to conserve space, as noted in the relevant issue.
status: ready

Allow SD Card Installation

---

src/status_im/group_settings/handlers.cljs

fixes #212
Clearing the chat history when line is still shown in Chats
-Open Status
-Click Chats Tab
-Chat with someone
-Clean the current chat history
-Back to Chats Tab
-Make sure `No messages` is displayed
status: ready

Clear :last-message when clearing chat history. Fixes #212

---

src/status_im/chat/handlers.cljs

fixes #1291 
Chat is deleted in Chats but after app relaunch it's shown again in Chats...
* Open Status
* Open Chats
* Delete some chat (e.g with Auction House)
* Close app
* Open app
* Check if Auction House is shown in Chats
status: ready

chat: fix broken chat delete logic

---

src/status_im/translations/fr.cljs

Updated to most recent english file.

Update to FR translation

---

package.json

fixes #1359
App stopped on edit Capture in profile
Fixed by upgrading `react-native-camera`
* Launch the app
* Sign into account 
* Edit profile (left top menu)
* Tap Edit (right top menu)
* Tap on profile image and select Capture
* Take a photo
status: ready

Upgraded react-native-camera. Fixes #1359

---

bots/demo_bot/bot.js
resources/status.js
src/status_im/chat/handlers/input.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/views/message/request_message.cljs
src/status_im/utils/types.cljs

Some changes that were done during hackathon and were included only in hackathon's version of app.
1. `text-message` can be used fro sending message from bot after command (if status.sendMessage is used, message will appear before command)
2. `from`/`to` props in context args for suggestions functions
3. `text-message` property and `status.sendMessage` method allows to send request from bot
4. ability to add some plain text to request message (instead of rendering command's preview )

Bot API improvements

---

src/status_im/chat/views/input/input.cljs
src/status_im/utils/views.clj

```clojure
;; Allows to write
(defview v [arg]
(letsubs [sub [:sub]]
[text (str sub arg)]))
;; instead of
(defview v [arg]
[sub [:sub]]
[text (str sub arg)])
```
In result `letsubs` can be resolved as let macro in Cursive and symbols defined in `letsubs` will be resolved too. `defview` is compatible with previous version.

letsubs macro

---

.re-natal
package.json
src/status_im/chat/handlers/input.cljs
src/status_im/chat/models/input.cljs

fixes #840 
- This will replace text-based emoticons with emojis in the chat. 
- This PR uses this very simple emoji package that provides a json containing all the emojis indexed by their names: https://github.com/muan/emojilib 
- Open Status
- Go to the chat and type one of the emoji name between `:` (ex:  `:smile:` `:+1:`  `:123:` `:cactus:` )
(all the keys of the following json are supported: https://github.com/muan/emojilib/blob/master/emojis.json )
status: ready

chat: implement emoji replace

---

src/status_im/contacts/handlers.cljs
src/status_im/data_store/realm/schemas/account/core.cljs
src/status_im/data_store/realm/schemas/account/v9/command_parameter.cljs
src/status_im/data_store/realm/schemas/account/v9/core.cljs

fixes #1210 
There was no text hint for the `@browse` and `/location` commands after the first run of the application. This was caused by the fact that the schema for `command-parameter` didn't include a `:placeholder` attribute so when the browse contact is saved the placeholder text is lost.
I added a migration to add placeholder as an optional attributes (not all commands seem to have it). In addition the migration function will also add back the missing placeholder attribute so that users already affected by the bug will get the placeholder back automatically.
- Open Status not 1st time
- Open console
- type @browse or select it from commands. check if URL is shown after it
- delete browse command
- type /location or select it from commands. check if URL is shown after it Address
If …

Missing hints for @browse and /location (#1210)

---

src/status_im/android/platform.cljs
src/status_im/components/drawer/styles.cljs
src/status_im/components/status_view/view.cljs
src/status_im/profile/screen.cljs
src/status_im/utils/utils.cljs

fix #1247
`(.startsWith "#你好" "#")` not works, but both
`(.startsWith "#你好" "#你")` and `(.startsWith "#abc" "#")` works.

status hashtags, android: fix #1247

---

src/status_im/utils/handlers.clj

Before this commit 
```clojure
(handlers->
(fn [db [_ data]]
(account-update db data))
save-account!
broadcast-account-update)
```
was expanded as 
```clojure
(fn*
([db# event#]
(let [db# (or ((fn [db [_ data]] (account-update db data)) db# event#) db#)
db# (or (save-account! db# event#) db#)
db# (or (broadcast-account-update db# event#) db#)]
db#)))
```
which means that if `save-account!` returns not nil value but not db the flow will be broken.
This fix doesn't guaranty that problem will not appear anymore, but `handlers->` is a temporary solution before refactoring and it should work fine for now.
```clojure
(fn*
([db# event#]
(let [db# (let [new-db# ((fn [db [_ data]] (account-update db data))
db#
event#)]
(if (map? new-db#)
new-db#
db#))
db# (let [new-db# (save-account! db# event#)] …
```

re-frame post migration bugs (part 2)

---

src/status_im/profile/photo_capture/screen.cljs

fixes #1363
The user picture doesn't change if tapping on the "Camera" button twice
Reduce captured photo size.
_TODO_ Disable button after first tap
- Launch app "Status"
- Login with valid credentials
- Go to Profile
- Click on the button with three points and tap on the "Edit" button
- Tap on the user picture
- Select "Capture"
- Tap on the "Camera" button twice or more
status: wip

[WIP] Prevent double tap when capturing profile picture

---

src/status_im/chat/styles/input/input.cljs
src/status_im/chat/views/input/input.cljs

fixes #1354 
This PR fixes overflowing characters after  any `/command` input if the text is too long and doesn't fit on one line together with `/command` prefix. 
The reason why it was happening was that minimal width of the input element for commands was set to 200, which together with `/command` width was often more then width of the wrapping container element.
Now the minimal width for the input element is computed by subtracting `/command` width from enclosing container-width.
- Open Status
- Open console
- Select `/confirmation-code` …

chat: fix input length styling after commands

---

bots/wallet/bot.js
bots/wallet/translations.js
src/status_im/chat/handlers/commands.cljs
src/status_im/chat/handlers/console.cljs
src/status_im/chat/handlers/input.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/chat/models/input.cljs
src/status_im/chat/views/message/request_message.cljs
src/status_im/commands/handlers/jail.cljs

I've changed the way command's structure look like (for instance, there is no more `:command-message`) and fixes #1396
Probably it also solves other issues.

Names for send/request messages in group chat (#1396); refactoring of command sending

---

bots/console/bot.js

fixes #1438 
Preview for phone command was missing, as a result, internal piece of app-db was displayed whenever `/phone` command was entered in the console, this PR fixes it by correct preview/shortPreview functions which pull just relevant data (phone number) in right markup for display.
- Open Status
- Open console from contacts
- Isse an `/phone` command
- Check if the `/phone` command message is displayed in a correct way (only command prefix + phone number)
status: …

console: add preview for phone command

---

src/status_im/chat/handlers/input.cljs
src/status_im/chat/models/input.cljs
src/status_im/chat/subs.cljs
src/status_im/chat/utils.cljs
src/status_im/chat/views/api/choose_contact.cljs
src/status_im/chat/views/api/geolocation/styles.cljs
src/status_im/chat/views/api/geolocation/views.cljs
src/status_im/chat/views/input/input.cljs
src/status_im/commands/utils.cljs
src/status_im/components/react.cljs

This PR aims to solve two problems:
1) The `input` model's code is too complex and cannot be understood by everyone;
2) There is some logic in `input` view, and this logic should be moved to `input` model or subscriptions/handlers.
I've also moved `geolocation` views to `status.chat.views.api`, and reduced the number of dispatch calls for input (i.e. created a separate handler `:update-input-data` which is now called instead of 3 handlers in a row).

Simplification and comments for `input` model

---

env/dev/user.clj
figwheel-bridge.js
project.clj

Upgraded to latest figwheel/cljsbuild. Adapted `builds` syntax so that we can perform the following:
* lein doo phantom test once
* lein cljsbuild once android
Note `figwheel` offers new features we might want to leverage (e.g. it would be nice to be able to execute test w/o starting figwheel /re-frisk..)
To be addressed in a subsequent PR.
status: ready

Upgraded figwheel/cljsbuild.

---

src/status_im/chat/handlers.cljs

fixes #1421 
The error message remains on Chat switching 
Log in to the app
Go to the Contact -> Jarrad
Use send command to send 1000 amount (e.g."Send Jarrad 1000") As a result, error message is shown.
Go to the wallet or another chat
Go to chat Jarrad
There is no error
status: ready

Make sure validation-messages are nil when navigating to a chat

---

src/status_im/translations/en.cljs
src/status_im/translations/es.cljs

* Fix `location` translation pasted to `command`
* Fix Status (product name) translated to Spanish and lowercased in English too
* More natural Spanish translations
status: ready

Refine translations/es.cljs, fix en `:send-command-description`

---

bots/console/bot.js

fixes #1207 
When you type "," to Console it autocomplete to "console" and "web3". This is due to a bug in the Console parsing code where "," is treated differently from characters like ".",  resulting in an empty form which matches the top level in DOC_MAP. The pull request checks if we are the very beginning of parsing a form and makes sure "," stays intact, like it's done with other special characters.
- Open Status
- Chat with console
- Type "," and check that it doesn't suggest anything
- Unknown: What is the grammar of a suggestion? …

console: fix bad suggestion (#1207)

---

src/status_im/translations/ms.cljs

Translated the new added/fixed strings on the tracked en.cljs following commit https://github.com/status-im/status-react/commit/5051d1ce9e3e7acae6266827092db735c0e31443 and https://github.com/status-im/status-react/commit/41ee6bfa89f4ea8bb98ea52565bc07da317b05c8 plus properly translated the word `Wallet`.

Update Bahasa Malaysia translation

---

src/status_im/translations/it.cljs
src/status_im/translations/ru.cljs
src/status_im/translations/vi.cljs

fixes #1481 
For 1-1 chats that were created before changing device language (and Status UI language): chat toolbar status contains [missing {{Number}} value] ... instead of "4 hours ago", "Online" etc
* Open Status when device language is in English
* Create some 1-1 chat
* change device language to Russian
* launch Status
* Open created 1-1 chat and check the bar above message area
status: ready

Fixed incorrect message keys

---

src/status_im/components/sticky_button.cljs
src/status_im/utils/utils.cljs
test/cljs/status_im/test/runner.cljs
test/cljs/status_im/test/utils/utils.cljs

fixes #1488 
Can tap several times on Save button that causes multiple group chats been created with same name 
* Open Status
* Go to Chats
* Create new group chat
* Tap several times on Save button
status: ready

Multiple hit on save should not create multiple groups

---

bots/wallet/bot.js

fixes #1489 
Previously, we displayed transaction fee as result of the `web3.fromWei` call without any further formatting, which sometimes caused inconsistent fee values even for the same tx amount and slider position, because they differed in precision.
This PR introduces change where transaction fee is always formatted to 7 decimal places, so it stays consistent.
- Open Status
- Open 1-1 chat
- Enter `/send` command, choose contact and enter tx value '10'
- Move tx fee slider to the right (maximal fee)
- Change the tx value to '1'
- Change …

wallet: always displays fee with fixed precision

---

src/status_im/chat/handlers/commands.cljs
src/status_im/data_store/messages.cljs
src/status_im/utils/utils.cljs
test/cljs/status_im/test/utils/utils.cljs

Implement simple preview caching for command messages in realm-db, so if preview was already loaded and displayed, no `:request-command-preview` with jail call is made. 
Next steps are to implement default `preview/shortPreview` functionality of command messages on top of this caching, however, there are some issues I would like to discuss first with @rasom @alwx and @jeluard -
* I think it would be wise to change semantics of how command previews registered from javascript API (see for example …

chat, data, utils: add implementation of simple preview caching

---

bots/console/bot.js
bots/console/test.js
src/status_im/chat/subs.cljs

fixes #1207 (partially)
Typing ')' and 'a)' in Console autocompletes wrongly to "console" and "web3". This is due to a parsing bug where a single unbalanced ')' is counted as nesting, resulting in a wrongly parsed code form ('').
Additionally, another problem was surfaced while working on this issue and in the #1207 thread. It isn't currently clear what suggestions should be allowed, and this seems like an open problem. I included an ad hoc test script that lets us define inputs and their expected suggestions. Let me know if you want me to squash this or get rid of it / change it.
For example, is 'a(' in invalid suggestion? If we want to allow Javascript, the following code is valid:
```
var a = console.log;
a("foo");
```
So the behavior would be expected. To me that seems like a separate …

Bug/bad suggestion #1207

---

src/status_im/chat/handlers/commands.cljs

fixes #1499
Don't put nil (null) values into realm store where schema doesn't allow it
- Clean phone settings and install Status app from scratch
- Open Status
- Set password
- Confirm password
- App doesn't crash as before this bugfix
status: ready

fix #1499 chat: don't persist null properties

---

src/status_im/android/core.cljs
src/status_im/ios/core.cljs
src/status_im/utils/utils.cljs

Added a basic exception handler displaying exceptions details in a popup for both `dev` and `prod` environment.
This servers 2 purposes:
* do not crash app because of Clojure issues in `prod`
* get more details about issues
This can be modified to display more info or to hook with `instabug` or similar.
status: wip

Added basic exception handler.

---

bots/wallet/bot.js

fixes #1501 
Previously, to be able to format fractional number to fixed amount of decimal places, string returned from `web3.fromWei` call was parsed into native js float type with `parseFloat` function. Unfortunately for some amounts (not immediately obvious during developer testing), this is not enough, as native js float has problems with precision, so slightly different sum was displayed between fee/amount edits.
This PR solves it by parsing `web3.fromWei` result directly into BigNumber type (this type should be returned from …

fix #1501 wallet: display right fee amount

---

src/status_im/chat/handlers/input.cljs

fixes #1390 
When the input field includes an unmatched " in the input-text, there's a mismatch between the parsed command-args and the length of the text field, causing text selection to be out of bounds. By bounding the new selection to a maximum of the input text length, this is avoided.
command-args: ["/request" "Abandoned Worried Wolf"]
input-text: "/request \"Abandoned Worried Wolf"]
new-sel: (before PR): 33 
**new-sel: (after PR): 32**
command-args: ["/request" "Abandoned Worried Wolf"]
input-text "/request \"Abandoned Worried Wolf\""
new-sel: (before PR): 33 
new-sel: (after PR): 33
- Open Status
- Chat with a user that has many parts in their name (e.g. "Abandoned Worried Wolf")
- Type `/request` and select …

chat: fix #1390, selection OOB

---

src/status_im/new_group/screen_private.cljs
src/status_im/new_group/views/chat_group_settings.cljs

fixes #1488 
@jeluard did all the hard work of implementing once-only option for `:on-press` handlers, this PR just uses the option when creating new group chat :)
Additional issue which is probably not in scope of this PR - it's still totally possible to create duplicate group chats with same set of participants and same name - should this be actually allowed, or do we wan't to enforce some rules like at least set of participants or name must be different ? What do you think @rasom @jarradh ?
- Open Status
- Create new group chat
- Try to …

fix #1488 new_group: once-only handler for save

---

src/status_im/translations/fr.cljs

"Address" in english is "Adresse" in French + Everything in the page is in Zero infinitive excect this "Entrez Addresse", which sounded weird.

translations: Fix french translation

---

src/status_im/profile/screen.cljs

fixes #1171 
Before this patch there was one menu remaining that allowed removing "unremovable" contacts.
- Open Status
- Open Console Profile
- Edit Profile
- Delete Contact option should not be visible
status: ready

fix #1171: hide remove option from profile menu for unremovable contacts

---

bots/console/bot.js

fixes #1467 
Preview/shortPreview console bot option for confirmation command response was not defined, this simple fix just adds it.
In the very near future, we will provide some meaningful default preview/shortPreview function for commands/command-responses so it's not necessary to define it if nothing more then simple param display is required
- Open Status
- Open Console
- Send `/confirmation-code` command with some number
- Observe that confirmation code is rendered correctly
[comment]: # (PRs will only be accepted if squashed into …

fix #1467 console: confirmation code preview

---

src/status_im/transactions/views/list_item.cljs

Transactions with 15 significant digits crashes the app due to something weird going on in the Clojurescript -> web3 -> BigNumber call chain. This fix rounds transactions to a maximum 14 significants digits which ensures the app doesn't crash.
- Open Status (iOS)
- Ensure you Ether on your account
- /send PERSON 0.111122223333444
- Notice that app no longer crashes
status: wip

fix #1050 transaction view: app crash

---

src/status_im/chat/handlers/commands.cljs

Previously, we were not checking if the `:request-command-data` call (calling jail) was actually returning something meaningful and just blindly updated the `:message-data` in db with call result, unfortunately this resulted in lot of `:message-data` entries where value under particular message-id was nil (mainly for previews/shortPreviews).
As we check the map under `[:message-data :preview]` path with `contains?` for particular message-id before deciding if we want to fetch/re-fetch message preview/shortPreview, sometimes we erroneously …

fix #1469 chat: location is shown as plaintext

---

src/status_im/chat/handlers.cljs
src/status_im/chat/handlers/receive_message.cljs
src/status_im/chat/handlers/send_message.cljs
src/status_im/protocol/chat.cljs
src/status_im/protocol/core.cljs
src/status_im/protocol/handlers.cljs
src/status_im/utils/clocks.cljs
test/cljs/status_im/test/runner.cljs
test/cljs/status_im/test/utils/clocks.cljs

fixes #1015, #1195 and #1051 
This commit ensures messages are ordered correctly when participants join and leave a group chat. Specifically, the last received message will appear last. Previously the user and chat clock was queried and updated in an ad hoc manner. With this change there are only two clock changes to keep track of. Here's the basic algorithm:
Sending messages:
time = time+1;
time_stamp = time;
send(message, time_stamp);
Receiving messages:
(message, time_stamp) = receive();
time = max(time_stamp, time)+1;
(See https://en.wikipedia.org/wiki/Lamport_timestamps)
Note that this means we can get rid of all the non-message clock queries and updates.
For #1015:
-  A sends message to public chat
-  B joins public chat, sees no message from A, sends message
- A sees message, sends …

chat, protocol: Introduce Lamport clock semantics for message order

---

doc/refactoring-guidelines.md

Fixes #1495
Now that a few developpers have been working / are working on refactoring, I thought it might be worth taking the proposal made by @jeluard 2 weeks ago and turn it into an actual document.
I added the suggestions made into the issue and on Slack, especially those regarding the splitting of the work into PRs.
From my short experience on the project I find it easier to first jump on the code conventions and hierarchy refactoring as it doesn't require to change any behavior and allows one to explore the code before getting into the harder parts. So I propose to make it into PR #1
For the PR #3 I was just not sure what the steps could turn into during an actual refactoring, so if someone can complete them, add example that would be great.
One of the main reason I do this PR is to …

Refactoring guidelines draft

---

src/status_im/components/drawer/view.cljs
src/status_im/ui/screens/db.cljs
src/status_im/ui/screens/profile/db.cljs
src/status_im/ui/screens/profile/edit/views.cljs
src/status_im/ui/screens/profile/events.cljs
src/status_im/ui/screens/profile/photo_capture/views.cljs
src/status_im/ui/screens/profile/styles.cljs
src/status_im/ui/screens/profile/views.cljs

- use fx and cofx
- use ns keys for events
- moved some event logic that was in the view into the events
- keep state locally in the drawer
- no subscriptions
- specs
play around with profile editing and contact profile to see if anything broke
- change status from drawer
- change name from drawer
- edit profile
- try username "wallet" (should be in red and if saved go back to previous name)
- change image profile

Feature/profile refactoring: PR #2 Functional changes
