src/status_im/chat/views/message.cljs
Fixes https://github.com/status-im/status-react/issues/249
=> Correct identicon in a group chat (#249)

src/status_im/accounts/handlers.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/animation.cljs
=> Wallet: create wallet chat after account recovery

src/status_im/components/text_field/view.cljs, src/status_im/contacts/styles.cljs, src/status_im/contacts/views/new_contact.cljs, src/status_im/translations/en.cljs
https://github.com/status-im/status-react/issues/243
=> More clear validation message in "Add new contact" form (#243)

package.json
the problem was in react-native-android-sms-listener. Forked the one from alwx and fixed it. I also submitted a pull-request, but until it gets merged, we can use my fork.
=> fixed exception in react-native-android-sms-listener; fixes #267

android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/values/styles.xml, ios/StatusIm.xcodeproj/project.pbxproj, src/status_im/chat/constants.cljs, src/status_im/chat/styles/message_input.cljs, src/status_im/chat/styles/plain_message.cljs, src/status_im/chat/styles/response.cljs, src/status_im/chat/views/command.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/plain_message.cljs, src/status_im/chat/views/response.cljs, src/status_im/contacts/views/contact.cljs, src/status_im/group_settings/screen.cljs
Adds multiline text views for plain messages.
Also:
1) Updates control styles for Android (correct selection color)
2) Removes my team certificate information from IOS project
=> Multiline text input (#255)

src/status_im/components/text_field/view.cljs, src/status_im/db.cljs, src/status_im/new_group/handlers.cljs, src/status_im/new_group/screen.cljs, src/status_im/new_group/styles.cljs, src/status_im/new_group/validations.cljs, src/status_im/new_group/views/contact.cljs, src/status_im/translations/en.cljs
1. Updated styles for new group-chat screen
2. clojure.spec-based validation functions
3. UI updates to make everything look better
fixes #266
fixes #253
=> Correct styles for new group chat screen (#253 and #266)

src/status_im/chat/views/new_message.cljs, src/status_im/profile/validations.cljs, src/status_im/utils/phone_number.cljs
Read my comment here: https://github.com/status-im/status-react/issues/259
fixes #259
=> Extended phone number validation (#259)

env/dev/env/android/main.cljs, src/status_im/chat/handlers.cljs, src/status_im/models/pending_messages.cljs, src/status_im/protocol/group.cljs, src/status_im/protocol/handlers.cljs, src/status_im/protocol/listeners.cljs, src/status_im/protocol/web3/delivery.cljs, src/status_im/transactions/subs.cljs, src/status_im/utils/hex.cljs
=> Group chat: stop watching of group's topic & handle new participant

src/status_im/accounts/handlers.cljs, src/status_im/accounts/login/handlers.cljs, src/status_im/contacts/handlers.cljs
=> Allow the user to start using chat after account's creation 

src/status_im/accounts/recover/handlers.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/wallet_chat.cljs, src/status_im/handlers.cljs
=> Wallet dapp is created before contacts sync 

src/status_im/contacts/views/new_contact.cljs, src/status_im/data_store/realm/core.cljs, src/status_im/translations/en.cljs
=> Fixes bugs related to "Add new contact" form (#308, #309)

src/status_im/contacts/handlers.cljs, src/status_im/discovery/handlers.cljs, src/status_im/protocol/listeners.cljs
fixes #318
populate discoveries with statuses received from contacts
allow user to receive his own statuses
=> Discoveries bugs (#318)

src/status_im/components/drawer/styles.cljs, src/status_im/components/drawer/view.cljs, src/status_im/components/styles.cljs, src/status_im/components/text_field/view.cljs, src/status_im/profile/handlers.cljs, src/status_im/profile/screen.cljs
=> Status & Name, quick profile change in drawer (#294), length limit (#324)

src/status_im/accounts/handlers.cljs, src/status_im/accounts/login/handlers.cljs, src/status_im/android/core.cljs, src/status_im/chat/handlers.cljs, src/status_im/db.cljs, src/status_im/discovery/handlers.cljs, src/status_im/translations/en.cljs
=> Make console the default on-boarding (#280)

src/status_im/chat/handlers/receive_message.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/datemark.cljs, src/status_im/chat/styles/message.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/datemark.cljs, src/status_im/chat/views/message.cljs, src/status_im/translations/en.cljs, src/status_im/utils/datetime.cljs
=> Date indicators in chat (#282)

src/status_im/components/chat_icon/styles.cljs, src/status_im/profile/handlers.cljs, src/status_im/profile/screen.cljs, src/status_im/profile/styles.cljs
Fixes https://github.com/status-im/status-react/issues/314
=> Updated profile view (#314)

src/status_im/chat/handlers/wallet_chat.cljs, src/status_im/components/toolbar/view.cljs, src/status_im/contacts/screen.cljs, src/status_im/contacts/subs.cljs
=> Fixes bugs related to contacts list screen (#316, #292)

src/status_im/chat/views/request_message.cljs
=> Tappable request message (#283)

resources/console.js, resources/status.js, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/styles/response.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/command.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/response.cljs, src/status_im/chat/views/staged_command.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/components/status.cljs, src/status_im/models/commands.cljs, src/status_im/translations/en.cljs, src/status_im/utils/datetime.cljs
=> Password Request (#286)

src/status_im/components/main_tabs.cljs, src/status_im/components/tabs/styles.cljs, src/status_im/components/tabs/tab.cljs, src/status_im/components/tabs/tabs.cljs, src/status_im/navigation/handlers.cljs
Fixes https://github.com/status-im/status-react/issues/293
=> Tab text animations (#293)

src/status_im/chat/screen.cljs, src/status_im/chat/sign_up.cljs, src/status_im/chat/styles/message.cljs, src/status_im/chat/utils.cljs, src/status_im/chat/views/message.cljs, src/status_im/data_store/realm/schemas/account/core.cljs, src/status_im/data_store/realm/schemas/account/v2/contact.cljs, src/status_im/data_store/realm/schemas/account/v2/core.cljs
Partially done.
1) Photos and statuses for every user, not only `console`;
2) Fix for status saving (missing db property restored).
=> Beginning of chat (#296)

src/status_im/chat/views/message.cljs
fixes https://github.com/status-im/status-react/issues/313
=> No more bouncing in messages animation (#313)

src/status_im/android/platform.cljs, src/status_im/chat/styles/screen.cljs, src/status_im/chat/views/toolbar_content.cljs, src/status_im/components/chat_icon/screen.cljs, src/status_im/components/chat_icon/styles.cljs, src/status_im/components/toolbar/styles.cljs, src/status_im/components/toolbar/view.cljs, src/status_im/ios/platform.cljs
Fixes https://github.com/status-im/status-react/issues/301
=> Chat header text & arrow alignment off (#301)

src/status_im/chat/handlers.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/toolbar_content.cljs, src/status_im/chats_list/views/inner_item.cljs, src/status_im/components/drawer/view.cljs, src/status_im/contacts/views/contact_inner.cljs, src/status_im/discovery/views/discovery_list_item.cljs, src/status_im/translations/en.cljs
=> changed to GFYCat-style naming convention

src/status_im/components/chat_icon/styles.cljs, src/status_im/components/drawer/styles.cljs, src/status_im/profile/screen.cljs, src/status_im/profile/styles.cljs
=> Status styles in profile and drawer (#350)

src/status_im/commands/handlers/loading.cljs, src/status_im/new_group/validations.cljs, src/status_im/profile/validations.cljs, src/status_im/utils/homoglyph.cljs
=> Command name validation (#235)

src/status_im/accounts/handlers.cljs, src/status_im/accounts/login/handlers.cljs, src/status_im/accounts/views/account.cljs, src/status_im/android/core.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/views/toolbar_content.cljs, src/status_im/chats_list/screen.cljs, src/status_im/contacts/handlers.cljs, src/status_im/db.cljs, src/status_im/ios/core.cljs, src/status_im/navigation/handlers.cljs
=> Navigator fixes (#343)

resources/wallet.js, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/animation.cljs, src/status_im/chat/handlers/wallet_chat.cljs, src/status_im/chat/styles/dragdown.cljs, src/status_im/chat/styles/response.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/response.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/models/commands.cljs
=> Various !browse command issues on open (#349)

src/status_im/chat/styles/message.cljs, src/status_im/chat/views/message.cljs, src/status_im/chats_list/views/chat_list_item.cljs, src/status_im/chats_list/views/inner_item.cljs, src/status_im/components/chat_icon/screen.cljs, src/status_im/components/chat_icon/styles.cljs, src/status_im/data_store/messages.cljs, src/status_im/data_store/realm/messages.cljs, src/status_im/translations/en.cljs
Fixes #362 
fixes #364
fixes #367
=> Several UI fixes (#362, #364, #367)

src/status_im/chat/subs.cljs
=> Fix for suggestions bar (#370)

src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/receive_message.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chats_list/views/inner_item.cljs, src/status_im/data_store/realm/messages.cljs, src/status_im/data_store/realm/schemas/account/core.cljs, src/status_im/data_store/realm/schemas/account/v3/chat.cljs, src/status_im/data_store/realm/schemas/account/v3/core.cljs, src/status_im/data_store/realm/schemas/account/v3/message.cljs, src/status_im/protocol/web3/delivery.cljs
Fixes #224 
Uses Lamport timestamps (https://en.wikipedia.org/wiki/Lamport_timestamps) algorithm cause it is much simpler than vector clock, but works perfect in this case.
=> Correct ordering of messages (#224)

src/status_im/chat/screen.cljs, src/status_im/chat/views/message.cljs
=> User icons in group chat (#378)

ios/StatusIm/Info.plist, resources/commands.js, src/status_im/chat/views/response.cljs, src/status_im/translations/en.cljs
=> !browse bugs

package.json, src/status_im/android/platform.cljs, src/status_im/chat/styles/datemark.cljs, src/status_im/chat/styles/message.cljs, src/status_im/chat/styles/suggestions.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/chat/views/suggestions.cljs, src/status_im/translations/en.cljs
fix https://github.com/status-im/status-react/issues/344
But it is probably not the best idea to merge it now 'cause RC version of React Native may be unstable. 
Waiting for 0.36.0.
=> Toolbar with dark content (#344), React Native 0.36 support

modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/java/com/statusim/module/StatusConnector.java, modules/react-native-status/android/src/main/java/com/statusim/module/StatusMessages.java, modules/react-native-status/android/src/main/java/com/statusim/module/StatusModule.java, modules/react-native-status/android/src/main/java/com/statusim/module/StatusService.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/pom.xml, src/status_im/components/status.cljs, src/status_im/transactions/handlers.cljs
Integrates https://github.com/status-im/status-go/pull/56
=> Add discardTransaction method to react-native-status module

package.json, src/status_im/chats_list/screen.cljs, src/status_im/chats_list/styles.cljs, src/status_im/contacts/screen.cljs, src/status_im/contacts/styles.cljs, src/status_im/contacts/views/contact.cljs
=> Upgrade react-native-action-button (#395, #398)

src/status_im/contacts/styles.cljs, src/status_im/contacts/views/new_contact.cljs
=> Add contact form fixes (#405)

.gitignore, env/dev/env/android/main.cljs, env/dev/env/android_test/main.cljs, env/dev/user.clj, figwheel-bridge.js, project.clj, run-osx.sh, src/cljsjs/react.cljs, src/cljsjs/react/dom.cljs, src/cljsjs/react/dom/server.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/chat/views/response.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/components/refreshable_text/view.cljs, src/status_im/components/status.cljs, src/status_im/utils/js_resources.cljs
Instead of 
```
lein figwheel android
```
you can run 
```
lein repl
```
and javascript files from `resources` dir will be reloaded on changes.
=> Reloadable js resources for jail

src/status_im/chat/constants.cljs, src/status_im/chat/styles/message_input.cljs, src/status_im/chat/styles/plain_message.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/plain_message.cljs
=> Fix for multiline message input (#397)

src/status_im/transactions/screen.cljs, src/status_im/transactions/styles.cljs, src/status_im/transactions/views/transaction_page.cljs
Fixes #407
Looks better now
**Before**
**After**
=> UI fixes for transaction screen (#407)

src/status_im/contacts/handlers.cljs
=> Visual feedback after add contact (#315)

src/status_im/chat/styles/message.cljs, src/status_im/chat/views/message.cljs
=> Updated animation (#418)

src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/send_message.cljs
=> Fix for inconsistent gap between messages (#421)

resources/commands.js, resources/status.js, resources/wallet.js, src/status_im/accounts/styles.cljs, src/status_im/accounts/views/wallet_qr_code.cljs, src/status_im/android/core.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/requests.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/screen.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/chat/views/response.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/commands/utils.cljs, src/status_im/contacts/handlers.cljs, src/status_im/contacts/styles.cljs, src/status_im/contacts/views/contact.cljs, src/status_im/contacts/views/contact_list.cljs, src/status_im/ios/core.cljs, src/status_im/models/commands.cljs, src/status_im/navigation/handlers.cljs, src/status_im/qr_scanner/screen.cljs, src/status_im/transactions/handlers.cljs, src/status_im/translations/en.cljs
=> Feature: new wallet flow

resources/commands.js, resources/console.js, resources/status.js, resources/wallet.js, src/status_im/chat/views/suggestions.cljs
=> Command list (#441)

.gitignore, android/app/build.gradle, android/app/src/main/java/com/statusim/MainApplication.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, ios/StatusIm.xcodeproj/project.pbxproj, ios/StatusIm/AppDelegate.m, ios/StatusIm/Info.plist, package.json, src/status_im/chat/handlers.cljs, src/status_im/chat/sign_up.cljs, src/status_im/chat/views/message.cljs, src/status_im/components/drawer/styles.cljs, src/status_im/components/drawer/view.cljs, src/status_im/translations/en.cljs
Instabug allows testers to report feedback, record videos and screenshots within the application.
=> Instabug Integration

src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/data_store/messages.cljs, src/status_im/models/commands.cljs
=> prefill response parameters with request data

src/status_im/chat/handlers.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/screen.cljs, src/status_im/chat/views/actions.cljs, src/status_im/components/chat_icon/screen.cljs, src/status_im/components/chat_icon/styles.cljs, src/status_im/components/sync_state/offline.cljs, src/status_im/components/sync_state/styles.cljs, src/status_im/contacts/handlers.cljs, src/status_im/data_store/realm/schemas/account/core.cljs, src/status_im/data_store/realm/schemas/account/v4/chat.cljs, src/status_im/data_store/realm/schemas/account/v4/core.cljs, src/status_im/protocol/handlers.cljs
=> Contact request bugs (#433)

android/app/BUCK, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/im/status/ethereum/MainActivity.java, android/app/src/main/java/im/status/ethereum/MainApplication.java, android/app/src/main/java/im/status/ethereum/RootUtil.java, ios/StatusIm.xcodeproj/project.pbxproj, modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/AndroidManifest.xml, modules/react-native-status/android/src/main/java/im/status/ethereum/module/ConnectorHandler.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/ServiceConnector.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusConnector.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusMessages.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusService.java, modules/react-native-status/ios/RCTStatus/pom.xml, test/clj/status_im/appium.clj
=> Change package name to im.status.ethereum

src/status_im/chat/handlers.cljs, src/status_im/db.cljs, src/status_im/handlers.cljs
=> Fix command/request message locking

src/status_im/discovery/screen.cljs, src/status_im/discovery/search_results.cljs, src/status_im/discovery/views/discovery_list_item.cljs, src/status_im/discovery/views/popular_list.cljs
=> Aliases in discovery (#477)

.re-natal, src/status_im/accounts/login/screen.cljs, src/status_im/accounts/recover/screen.cljs, src/status_im/android/platform.cljs, src/status_im/chat/views/command.cljs, src/status_im/chat/views/response.cljs, src/status_im/components/drawer/styles.cljs, src/status_im/components/drawer/view.cljs, src/status_im/components/main_tabs.cljs, src/status_im/components/react.cljs, src/status_im/components/status_view/view.cljs, src/status_im/components/toolbar/view.cljs, src/status_im/contacts/views/new_contact.cljs, src/status_im/discovery/views/discovery_list_item.cljs, src/status_im/new_group/screen.cljs, src/status_im/participants/views/remove.cljs, src/status_im/profile/screen.cljs, src/status_im/profile/styles.cljs, src/status_im/utils/utils.cljs
=> Blue hashtags (#435)

src/status_im/components/main_tabs.cljs, src/status_im/components/toolbar/view.cljs, src/status_im/discovery/handlers.cljs, src/status_im/discovery/screen.cljs, src/status_im/discovery/styles.cljs, src/status_im/discovery/views/popular_list.cljs, src/status_im/translations/en.cljs
=> Fixes for discover search input field (#478)

src/status_im/components/main_tabs.cljs, src/status_im/components/tabs/styles.cljs, src/status_im/components/tabs/tabs.cljs
=> Chats/Discover/Contacts tabs menu animation iOS (#488)

.re-natal, android/app/build.gradle, android/app/src/main/java/im/status/ethereum/MainApplication.java, android/settings.gradle, env/dev/env/android/main.cljs, ios/StatusIm.xcodeproj/project.pbxproj, ios/StatusIm/Info.plist, package.json, src/status_im/components/react.cljs, src/status_im/components/selectable_field/view.cljs, src/status_im/components/share.cljs, src/status_im/profile/handlers.cljs, src/status_im/profile/screen.cljs, src/status_im/translations/en.cljs, src/status_im/translations/es.cljs, src/status_im/translations/es_ar.cljs, src/status_im/translations/ru.cljs, src/status_im/translations/sw.cljs, src/status_im/translations/uk.cljs
=> Share Address/Public Key (#485)

ios/StatusIm/Info.plist
=> Portrait only on iOS (#494)

android/app/build.gradle, package.json
🎉 One of the most long-awaited and desired bug fixes is almost here! 😁
https://github.com/alwx/react-native-camera/commit/492d64eb4a4d51aa1bb9f6c664a929e27862624c
Because I don't have a Samsung device, I've used AWS Device Farm to test it, and the good news is that this fix works. I've tested it on Samsung Galaxy S6, S5 and emulator.
Will submit a PR to react-native-camera a bit later.
=> Orientation fix (#495)

project.clj, src/status_im/chat/handlers.cljs, src/status_im/chats_list/screen.cljs
=> Chat list order

src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/receive_message.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/data_store/realm/schemas/account/v4/chat.cljs, src/status_im/group_settings/handlers.cljs, src/status_im/group_settings/screen.cljs, src/status_im/new_group/handlers.cljs, src/status_im/protocol/core.cljs, src/status_im/protocol/group.cljs, src/status_im/protocol/handlers.cljs, src/status_im/protocol/listeners.cljs
Only admin can add/remove users from the group.
=> Group adding/removing

src/status_im/accounts/screen.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/views/message.cljs, src/status_im/chats_list/styles.cljs, src/status_im/data_store/messages.cljs
1. Latest message fix (#507)
2. Clock-value fix (it was possible for clock-value to be overridden in :add-chat handler)
3. **UI fix:** bottom margin for chats list
4. **UI fix:** `:bounces false` for accounts list
=> Several messaging fixes: latest message (#507), no more clock-value bugs, some UI fixes

src/status_im/chat/styles/screen.cljs, src/status_im/chat/views/bottom_info.cljs
=> Message delivery status in group chat

src/status_im/chat/subs.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/components/status.cljs
fix #524
From now only one response can be staged for any request message.
=> Fix creation of multiple accounts

resources/console.js
Fixes #517.
In this case it was much more difficult to find the bug than to fix it.
=> No more error when tapping on command suggestion icon (#517)

src/status_im/accounts/styles.cljs
Fixes #518.
The solution is easy and straightforward
=> Accounts list overlaps with "Switch user" (#518)

src/status_im/accounts/handlers.cljs, src/status_im/accounts/login/handlers.cljs, src/status_im/chat/handlers.cljs
=> Show password request only for a new account

src/status_im/components/drawer/view.cljs, src/status_im/profile/screen.cljs, src/status_im/utils/utils.cljs
Fixes #491.
Unfortunately, first change is still a bit slow, but everything else works fine.
=> Blue hashtags & new line fix (#491)

src/status_im/chat/handlers.cljs, src/status_im/data_store/chats.cljs, src/status_im/new_group/handlers.cljs, src/status_im/protocol/handlers.cljs
Fixes bugs at adding/removing to/from group chat related to inconsistent order of incoming messages.
fix #510
=> Group chat adding/removing bugs

android/app/build.gradle, ios/StatusIm.xcodeproj/project.pbxproj
This sets the gradle `versionCode` and `versionName` for Android app builds and should do a similar thing on iOS. 
I tested the Android version and it is fine, I didn't get a chance to test iOS version, please fix and merge without me.
=> git-commit and tag based versioning

.gitignore, resources/console.js, resources/status.js, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/console.cljs, src/status_im/chat/handlers/faucet.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/response.cljs, src/status_im/chat/views/suggestions.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/translations/en.cljs
=> !faucet command (#445)

src/status_im/chat/views/toolbar_content.cljs, src/status_im/protocol/handlers.cljs
=> More detailed information about syncing in toolbar

.re-natal, package.json, src/status_im/android/core.cljs, src/status_im/chat/constants.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/emoji.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/emoji.cljs, src/status_im/chat/views/message_input.cljs, src/status_im/chat/views/plain_message.cljs, src/status_im/components/react.cljs, src/status_im/ios/core.cljs
=> Emoji picker (#547)

src/status_im/contacts/handlers.cljs
=> :update-contact! handler fixed (#559)

src/status_im/components/main_tabs.cljs
=> Fix tabs white screen

resources/console.js, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/console.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/command.cljs, src/status_im/chat/views/plain_message.cljs, src/status_im/chat/views/request_message.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/db.cljs, src/status_im/handlers.cljs, src/status_im/models/commands.cljs, src/status_im/transactions/handlers.cljs
=> Fix phone number validation, remove staged-commands leftovers 

src/status_im/components/carousel/carousel.cljs, src/status_im/components/carousel/styles.cljs, src/status_im/discover/screen.cljs, src/status_im/discover/styles.cljs, src/status_im/transactions/screen.cljs
=> Carousel calculation fixes (#561)

resources/console.js, src/status_im/chat/handlers/faucet.cljs
=> Strange suggestion behaviour (#602)

resources/commands.js
I'm not sure about validation message, maybe we need to show estimated gas there too.
=> !send command validation

src/status_im/accounts/styles.cljs, src/status_im/accounts/views/qr_code.cljs
=> Bigger area for cross on QR display screen (#610)

src/status_im/contacts/handlers.cljs, src/status_im/contacts/views/contact.cljs
=> Non-DApp Default Contact cannot receive messages or friend requests (#608)

src/status_im/translations/de.cljs
I will do more on this PR if during my tests today
=> Some German fixes

resources/commands.js, resources/console.js, src/status_im/i18n.cljs, src/status_im/translations/fi.cljs
=> translations: add fi translation

src/status_im/accounts/recover/handlers.cljs
=> accounts: add a random status to a recovered account #637

src/status_im/chat/constants.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/suggestions.cljs, src/status_im/chat/views/command.cljs, src/status_im/chat/views/message.cljs, src/status_im/chat/views/plain_message.cljs, src/status_im/chat/views/suggestions.cljs
Note: also removed the #594 fix, no longer seems necessary.
fixes #687
=> chat: change command char from ! to /  #687

src/status_im/accounts/handlers.cljs, src/status_im/contacts/handlers.cljs, src/status_im/data_store/realm/schemas/account/v1/contact.cljs, src/status_im/discover/handlers.cljs, src/status_im/protocol/core.cljs, src/status_im/protocol/discoveries.cljs, src/status_im/protocol/handlers.cljs, src/status_im/protocol/message.cljs, src/status_im/utils/handlers.cljs
=> Update public/private keys for discoveries (#557)

resources/console.js, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/sign_up.cljs, src/status_im/translations/en.cljs, src/status_im/utils/phone_number.cljs
=> Phone fixes (#539, #566, #634)

src/status_im/transactions/handlers.cljs, src/status_im/transactions/screen.cljs
=> App crash on empty password at confirmation (#644)

.re-natal, package.json, src/status_im/chat/views/message.cljs, src/status_im/components/react.cljs
=> Enable links within messages (#638)

package.json
Fixes #673 and makes emoji look fine
=> Emojis are cropped (#673)

src/status_im/navigation/handlers.cljs, src/status_im/profile/handlers.cljs
Is it a good idea to do not push view if it was previous, and just go back?
=> History tracking produces unexpected navigational flows Bug/#702

src/status_im/accounts/recover/screen.cljs
=> accounts: recover password no longer appears as clear text #732

src/status_im/navigation/handlers.cljs
Hi, Here is a fix for #747 
Solution as discussed with @rasom
=> Fix for :navigation-stack is grows on switching tabs #747

.re-natal, env/dev/env/android/main.cljs, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/views/message_input.cljs
=> Non-atomic send button, leads to sending multiple transactions if tapping fast (#667)

src/status_im/android/platform.cljs, src/status_im/chats_list/styles.cljs, src/status_im/contacts/styles.cljs, src/status_im/discover/screen.cljs, src/status_im/discover/styles.cljs, src/status_im/ios/platform.cljs
one more magic number, can't find why react-native-swiper positioned wrong
fix #635
=> Bottom of scrollable area hidden by nav bug (#635)

externs/externs.js, src/status_im/contacts/handlers.cljs
=> Generate address from public key for non-friends (#752)

src/status_im/contacts/validations.cljs, src/status_im/contacts/views/new_contact.cljs
=> Fix app crash adding new contact (#649)

resources/web3_init.js
1. For Android it is implemented on Java side as Android's js bridge supports sync communication
2. On iOS sync communication with js bridge isn't supported, so for dapps working over `http` protocol regular sync RPC request via XMLHttpRequest is used. Unfortunately, this will not work for dapps that are working over `https`.
fix #682
=> Support web3 sync methods

src/status_im/chat/handlers/send_message.cljs, src/status_im/contacts/handlers.cljs, src/status_im/utils/identicon.cljs, src/status_im/utils/js_resources.cljs
Simple fixes except the one form `.toString` to `str`. I'm not 100% sure about it.
@alwx @adrian-tiberius  what do you guys think?
=> fix kibit suggestions

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Provides a base template for creating Issues and Pull Requests
- View markdown files
- Comment on improvments 
status: ready
=> Github Templates

src/status_im/discover/subs.cljs
Fixes #778
To be honest, I don't completely understand why it doesn't work without this line.
=> Problems with discover updates (#778)

src/status_im/accounts/handlers.cljs, src/status_im/android/core.cljs, src/status_im/chat/constants.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/sign_up.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/toolbar_content.cljs, src/status_im/handlers.cljs, src/status_im/navigation/handlers.cljs
=> Weird behaviour if back is pressed in 2nd onboarding (#775)

src/status_im/chat/views/message_input.cljs, src/status_im/protocol/handlers.cljs
Fixes #659
Also, fixes a small, but critical bug caused by #809 (it was impossible to enter a password on iOS)
=> Updating profile names (#659), small bugfix

src/status_im/chat/handlers.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/views/response.cljs, src/status_im/commands/handlers/jail.cljs
=> Another attempt to fix #772

.re-natal, android/app/build.gradle, android/app/src/main/java/im/status/ethereum/MainApplication.java, android/settings.gradle, ios/StatusIm.xcodeproj/project.pbxproj, package.json, src/status_im/chat/handlers/console.cljs, src/status_im/components/network_info.cljs, src/status_im/translations/en.cljs
=> Showing device's IP (#807)

src/status_im/chat/handlers/webview_bridge.cljs
=> QR Code Scanning Addresses fix

src/status_im/profile/screen.cljs
fixes #867
...
- Open Status
- Edit profile
- Take a photo and save
status: ready
=> bug/cannot-capture-profile-image (#867)

src/status_im/transactions/handlers.cljs, src/status_im/utils/hex.cljs
=> Checking transaction recipient validity (#780)

src/status_im/navigation/handlers.cljs
fixes #643
...
- Open Status on Android
- Open contacts tab
- Press back button on a device
status: ready
=>  bug/white-screen-on-contacts-page (#643)

src/status_im/android/platform.cljs, src/status_im/components/toolbar_new/styles.cljs, src/status_im/contacts/styles.cljs, src/status_im/ios/platform.cljs, src/status_im/utils/styles.clj
Provides macro for declaring platfom specific styles.
status: ready
=> defstyles and defnstyles macro

resources/commands.js
Appended space to translation string `request_requesting` where it was missing.
fixes #873
=> i18n: fixes #873 and some german grammar

src/status_im/data_store/realm/contact_groups.cljs, src/status_im/new_group/handlers.cljs
=> Bug/new member to group [ui-refresh] (#943)

src/status_im/android/platform.cljs, src/status_im/components/context_menu.cljs, src/status_im/components/styles.cljs, src/status_im/components/toolbar_new/styles.cljs, src/status_im/components/toolbar_new/view.cljs, src/status_im/contacts/screen.cljs, src/status_im/contacts/styles.cljs, src/status_im/contacts/views/contact.cljs, src/status_im/contacts/views/contact_list.cljs, src/status_im/ios/platform.cljs, src/status_im/profile/edit/screen.cljs, src/status_im/profile/screen.cljs, src/status_im/profile/styles.cljs
fixes #911 and #834
status: ready
=> Bug/ui refresh leftovers (#911 and #834)

src/status_im/translations/en.cljs
make capitalization consistent
=> make capitalization consistent

src/status_im/contacts/screen.cljs, src/status_im/contacts/views/contact.cljs, src/status_im/navigation/handlers.cljs
=> Bug/Tap on contact has no effect if return from Wallet [ui-refresh] (#935)

env/dev/env/android/main.cljs, env/dev/env/ios/main.cljs, env/dev/user.clj, project.clj
- run "lein re-frisk use-re-natal" after running re-natal commands 
- run dev status 
- open http://localhost:4567/ in the browser
status: ready
=> Added re-frisk debugger

README.md
Update core contributors add mugshots
status: ready
=> Update core contributors add mugshots

resources/default_contact_groups.json, resources/default_contacts.json, src/status_im/contacts/handlers.cljs, src/status_im/data_store/realm/contact_groups.cljs, src/status_im/new_group/handlers.cljs, src/status_im/utils/js_resources.cljs
fixes #599
Implemented default contact groups json included two groups "Dapps" and "State of the Dapps"
- Open Status
- Open Contacts
status: ready
=> Feature/create state of the dapps group and default groups [ui-refresh] (#599)

modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/pom.xml
Fixes synchronization problem after migration to Ropsten Revival
=> Wipe lightchaindata on first run

src/status_im/accounts/recover/screen.cljs, src/status_im/transactions/screen.cljs
=> Bug/keyboard upcase #904

src/status_im/profile/screen.cljs
=> Bug/App crash if tap on Send transaction in Console/DApp profile (#964)

src/status_im/chat/views/message.cljs
=> Bug/default picture instead of user is  shown in chat (#961)

android/app/src/main/java/im/status/ethereum/MainApplication.java, modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/pom.xml, package.json, src/status_im/protocol/listeners.cljs, src/status_im/protocol/web3/delivery.cljs, src/status_im/protocol/web3/filtering.cljs, src/status_im/protocol/web3/transport.cljs, src/status_im/protocol/web3/utils.cljs
Adds support for [customized logging](https://github.com/status-im/status-go/pull/127) and [version 5 of whisper protocol](https://github.com/status-im/status-go/pull/129).
status: ready
=> Add customized logging for status-go on android and whisper ver5 support

src/status_im/chat/models/input.cljs
=> [chat-ui] request auto-selection on typing

src/status_im/components/common/common.cljs, src/status_im/components/text_input_with_label/styles.cljs, src/status_im/transactions/screens/pending-transactions.cljs, src/status_im/transactions/screens/transaction-details.cljs, src/status_im/transactions/styles/list_item.cljs, src/status_im/transactions/styles/password_form.cljs, src/status_im/transactions/styles/screens.cljs, src/status_im/transactions/views/list_item.cljs, src/status_im/transactions/views/password_form.cljs, src/status_im/translations/en.cljs
=> Bug/transactions ui refresh bugs (#981)

src/status_im/components/react.cljs, src/status_im/new_group/screen_private.cljs, src/status_im/new_group/views/chat_group_settings.cljs, src/status_im/new_group/views/contact_toggle_list.cljs, src/status_im/profile/edit/screen.cljs, src/status_im/transactions/handlers.cljs, src/status_im/transactions/screens/pending-transactions.cljs, src/status_im/transactions/screens/transaction-details.cljs
Fixes some leftovers from #953 review.
status: ready
=> Transactions UI refresh code review

resources/commands.js, resources/console.js
=> Correct keyboard types (#1002)

Jenkinsfile, README.md, test/appium/AppiumTests.iml, test/appium/pom.xml, test/appium/src/test/java/app/StatusApp.java, test/appium/src/test/java/screens/AbstractScreen.java, test/appium/src/test/java/screens/ChatScreen.java, test/appium/src/test/java/tests/AbstractTest.java, test/appium/src/test/java/tests/InitialRunTest.java, test/appium/src/test/java/utility/AppiumDriverBuilder.java
fixes #...
Enables Appium UI Automation tests to happen on Saucelabs, via Jenkins
status: ready
=> Appium Jenkins Test

src/status_im/chat/handlers/input.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/styles/input/input.cljs, src/status_im/chat/views/input/input.cljs
Fixes #999 
PR also contains a small layout fix for Android
=> Tap in input filed has no effect if message was sent with Enter [ui-refresh] (#999)

src/status_im/chat/handlers/input.cljs, src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/chat/subs.cljs
=> fix sending transactions from Wallet (#1003)

src/status_im/new_group/handlers.cljs
=> Bug/unexpected behaviour back button group chat [ui-refresh] (#993)

src/status_im/chat/styles/input/input.cljs, src/status_im/chat/views/input/input.cljs
Fixes #1013
Fixes #1017
Also updates the way text input works and makes its size correct even when the texts are big.
=> Better text input, fixes for #1013 and #1017

src/status_im/chat/handlers.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/input/input.cljs
Fixes #1020, #1021, #1024, #1026
=> Text input fixes (#1020, #1021, #1024, #1026)

src/status_im/chat/models/input.cljs, src/status_im/chat/views/input/input.cljs
=> fix suggestions on command selection (#1030)

Jenkinsfile, resources/commands.js, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/views/input/validation_messages.cljs, src/status_im/components/status.cljs, src/status_im/transactions/handlers.cljs, src/status_im/translations/en.cljs
=> Transaction fixes (#997, #1004)

externs/externs.js, src/status_im/chat/handlers/input.cljs, src/status_im/chat/views/message/request_message.cljs
=> Pre-filling /send response with amount (#996)

src/status_im/android/platform.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/screen.cljs, src/status_im/chats_list/screen.cljs, src/status_im/components/chat_icon/screen.cljs, src/status_im/components/chat_icon/styles.cljs, src/status_im/components/toolbar_new/styles.cljs, src/status_im/ios/platform.cljs, src/status_im/new_group/styles.cljs, src/status_im/new_group/views/group.cljs, src/status_im/profile/qr_code/screen.cljs, src/status_im/transactions/styles/screens.cljs
fixes #994
1 - dapp icon has been removed (discussed with @andmironov )
5 - will be in another PR
status: ready
=> Bug/ui refresh bugs (#994)

src/status_im/chat/handlers/receive_message.cljs, src/status_im/chat/views/input/input.cljs
=> Commands are not shown in group chat after member is added (#1031)

src/status_im/chat/screen.cljs
=> Bug/Wrong order of chat messages (#984)

src/status_im/chat/subs.cljs
=> fix text keyboard for /send /receive (#1045)

src/status_im/chats_list/styles.cljs
=> Bug/Number of unread messages is not centered on Chats screen (#1062)

src/status_im/chat/screen.cljs, src/status_im/chat/subs.cljs
=> Bug/The overlay should hide when the box is dragged beneath 50% (#1055)

env/dev/env/android/main.cljs, env/dev/env/ios/main.cljs, project.clj
=> Implemented sorted app-db and interface for pre-send function

src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/input.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/views/actions.cljs, src/status_im/chat/views/bottom_info.cljs, src/status_im/chat/views/input/input.cljs, src/status_im/chat/views/input/result_box.cljs, src/status_im/chat/views/input/web_view.cljs, src/status_im/commands/handlers/jail.cljs, src/status_im/protocol/web3/delivery.cljs, src/status_im/transactions/handlers.cljs
=> text-change optimisations (#971)

Jenkinsfile
Smaller slack notification from Jenkins
=> Compress Slack Notification

modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/android/src/main/java/im/status/ethereum/module/Web3Bridge.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, package.json, resources/web3_init.js, src/status_im/android/core.cljs, src/status_im/components/react.cljs, src/status_im/components/status.cljs, src/status_im/handlers.cljs, src/status_im/protocol/web3/utils.cljs, src/status_im/utils/ethereum_network.cljs, src/status_im/utils/web_provider.cljs
=> Send web3 RPC requests over RN module

src/status_im/android/platform.cljs, src/status_im/chat/screen.cljs, src/status_im/chat/styles/animations.cljs, src/status_im/chat/styles/screen.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/input/animations/expandable.cljs, src/status_im/chat/views/input/animations/responder.cljs, src/status_im/chat/views/input/utils.cljs, src/status_im/components/status_bar.cljs, src/status_im/contacts/views/contact_list_modal.cljs, src/status_im/ios/platform.cljs, src/status_im/transactions/screens/confirmation_success.cljs, src/status_im/transactions/screens/transaction_details.cljs, src/status_im/transactions/screens/unsigned_transactions.cljs
- Open Status
- Open Wallet
- Drag header
status: ready
=> Feature/Improve status-bar for android, implement animated expandable overlay

src/status_im/chat/handlers.cljs, src/status_im/chat/screen.cljs
=> Chat commands fix (#1070, #1082)

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/release/AndroidManifest.xml, bots/console/bot.js, ios/StatusIm.xcodeproj/project.pbxproj, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, package.json, postinstall.sh, resources/status.js, src/status_im/chat/constants.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/input.cljs, src/status_im/chat/sign_up.cljs, src/status_im/chat/views/message/request_message.cljs, src/status_im/components/permissions.cljs, src/status_im/components/status.cljs, src/status_im/handlers.cljs, src/status_im/profile/edit/screen.cljs, src/status_im/profile/handlers.cljs, src/status_im/translations/en.cljs
=> Runtime permissions (#762)

src/status_im/accounts/login/handlers.cljs, src/status_im/accounts/login/screen.cljs, src/status_im/accounts/login/styles.cljs
=> Bug/Crash on Login if tap Sign in button several times (#871)

src/status_im/qr_scanner/handlers.cljs
=> No camera is shown if scan QR. White screen is shown instead (#1120)

src/status_im/chat/styles/input/input.cljs, src/status_im/chat/views/input/input.cljs, src/status_im/chat/views/input/result_box.cljs, src/status_im/components/sync_state/styles.cljs
fixes #1138 #837
Fixed overlay for ios and added "offline" label into browse panel for both ios and android
"offline" label UI refresh will be implemented in another PR
status: ready
=> Bug/Offline message issues (#1138)(#837)

src/status_im/components/camera.cljs, src/status_im/profile/edit/screen.cljs, src/status_im/qr_scanner/handlers.cljs, src/status_im/translations/en.cljs
=> App crashes if access to camera was denied and user tries to scan QR or capture image (#1134)

src/status_im/chat/handlers/input.cljs, src/status_im/utils/phone_number.cljs
=> Invalid phone number error is shown for valid phone number (#1087)

bots/mailman/bot.js, src/status_im/bots/constants.cljs, src/status_im/chat/handlers/input.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/models/input.cljs, src/status_im/chat/utils.cljs, src/status_im/chat/views/message/message.cljs, src/status_im/chats_list/views/inner_item.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/contacts/handlers.cljs, src/status_im/contacts/subs.cljs, src/status_im/data_store/contacts.cljs, src/status_im/data_store/realm/schemas/account/v6/command.cljs, src/status_im/data_store/realm/schemas/account/v6/contact.cljs, src/status_im/handlers.cljs, src/status_im/models/commands.cljs
=> Hide mailman bot & inject mailman's commands as local commands (#1108, #848)

src/status_im/profile/screen.cljs
=> Fix "my profile" screen scroll (#1154)

src/status_im/components/contact/styles.cljs
=> Fix contact list checkbox position (#1157)

src/status_im/transactions/screens/transaction_details.cljs, src/status_im/transactions/screens/unsigned_transactions.cljs
fixes #1117 
- Added the offline label to the "Unsigned transactions" and "Transaction details" screens.
- In both screens, the confirm button and password form is hidden while offline.
status: ready
=> Add offline message to transaction screens (#1117)

src/status_im/chat/styles/input/input.cljs, src/status_im/chat/views/input/input.cljs
Fixes #1155 
Also fixes the Enter button bug
=> Input field takes 3 lines for 1-line browse command (#1155)

src/status_im/chat/views/input/animations/responder.cljs
=> Buf/If drag header up from the mid screen then it goes down first (#1096)

src/status_im/data_store/contacts.cljs
=> App crashes if delete Contact #1163

src/status_im/components/camera.cljs
Fixes #1148 (found the solution here: https://github.com/lwansbrough/react-native-camera/issues/446#issuecomment-282949181)
=> App asks for Microphone access while user tries to scan QR or capture an image [iOS only] (#1148)

android/app/src/main/AndroidManifest.xml, package.json, src/status_im/components/permissions.cljs, src/status_im/handlers.cljs
=> Geolocation permissions request on android

src/status_im/accounts/login/screen.cljs, src/status_im/accounts/login/styles.cljs
=> Feature/Activity indicator on Sign In (#1191)

src/status_im/contacts/handlers.cljs
=> Bug/App crashes if delete Demo bot from Contacts (#1170)

resources/default_contacts.json, src/status_im/chat/sign_up.cljs, src/status_im/components/contact/contact.cljs, src/status_im/contacts/handlers.cljs, src/status_im/contacts/screen.cljs, src/status_im/data_store/realm/schemas/account/core.cljs, src/status_im/data_store/realm/schemas/account/v7/contact.cljs, src/status_im/data_store/realm/schemas/account/v7/core.cljs
fixes #1171 
Now Console, Wallet and Browse contacts can't be removed.
status: ready
=> Unremovable contacts (#1171)

src/status_im/chat/handlers.cljs
=> Bug/No new messages are shown in 1-1 chat (#1016)

android/app/src/main/java/im/status/ethereum/MainApplication.java, package.json
=> inject web3 object before page loading on Android

src/status_im/chat/handlers.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/debug/handlers.cljs, src/status_im/utils/utils.cljs
Support for `status-dev-cli` 3.0 and fixes that allow developing bots easily and with features like hot reloading.
=> Devtools 3.0

modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
File is removed before each session, so in most cases it will be less than 5MB (Instabug's restriction).
=> Attach geth.log to Instabug report

src/status_im/debug/handlers.cljs
=> Feature/made  dapp-url optional, open chat after contact will be added

src/status_im/debug/handlers.cljs
PR for #1213 broke the build.
status: ready
=> Fix broken build

src/status_im/transactions/handlers.cljs
fixes #1215
Now the transaction timeout message, shown in chats, only appears to the transaction originator.
status: ready
=> Transaction timeout for another account (#1215)

src/status_im/android/core.cljs
=> Android device back button goes back in webview (#1204)

src/status_im/chats_list/screen.cljs
=> Remove white bar from empty chats screen (#1234)

src/status_im/transactions/handlers.cljs, src/status_im/transactions/screens/transaction_details.cljs, src/status_im/transactions/subs.cljs, src/status_im/transactions/views/list_item.cljs, src/status_im/translations/en.cljs
fixes https://github.com/status-im/status-go/issues/120
status: ready
=> Bug/"Error: transaction has been discarded" when deploying a contract (#status-go/issues/120)

src/status_im/protocol/handlers.cljs
=> schedule :check-sync outside eth.getSyncing callback

src/status_im/components/drawer/styles.cljs, src/status_im/components/drawer/view.cljs
=> Navigation in drawer

bots/demo_bot/bot.js, ios/StatusIm.xcodeproj/xcshareddata/xcschemes/StatusIm.xcscheme, modules/react-native-status/android/build.gradle, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/pom.xml, src/status_im/chat/handlers/commands.cljs, src/status_im/chat/handlers/input.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/components/status.cljs
Lock jail for 1 second after calling command's `:handler`
=> Persistent state in otto vm

bots/demo_bot/bot.js, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/input.cljs, src/status_im/chat/subs.cljs
=> Show suggestions with markup returned from bot's init function

bots/console/bot.js, bots/demo_bot/bot.js, modules/react-native-status/android/build.gradle, modules/react-native-status/ios/RCTStatus/pom.xml, resources/status.js, src/status_im/commands/handlers/jail.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/data_store/local_storage.cljs, src/status_im/data_store/realm/local_storage.cljs, src/status_im/data_store/realm/schemas/account/core.cljs, src/status_im/data_store/realm/schemas/account/v8/core.cljs, src/status_im/data_store/realm/schemas/account/v8/local_storage.cljs, src/status_im/utils/js_resources.cljs
`localStorage.setItem(key, value)` and `localStorage.getItem(key)` methods are added in jail. Data added using `setItem` is stored across sessions.
status: ready
=> localStorage in jail

modules/react-native-status/android/build.gradle, modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java, modules/react-native-status/ios/RCTStatus/RCTStatus.m, modules/react-native-status/ios/RCTStatus/pom.xml
=> Experimental PR for status-go's `hackaton` branch [WIP]

resources/default_contacts.json
Url was not correct after transferring Ethlance into district0x github
=> Fixed old URL for Ethlance

src/status_im/data_store/contacts.cljs
=> Bug/Unknown contact is automatically added (#1325)

src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/input.cljs
=> Bug/Webview is opened in half-screen (#1217)

README.md
fixes #1277 
...
- Open Status
- ...
- Step 3, etc.
status: <ready|wip>
=> #1277 Fixes README links, adds TODO links, addresses minor spelling

bots/console/translations.js, src/status_im/translations/zh_hans.cljs, src/status_im/translations/zh_hant.cljs, src/status_im/translations/zh_wuu.cljs, src/status_im/translations/zh_yue.cljs
Update Chinese translations
- Change device language setting to Chinese
- Launch app, confirm that Chinese is correctly reflected
status: ready
=> Update Chinese translations

src/status_im/translations/da.cljs
fixes #...
...
- Open Status
- ...
- Step 3, etc.
status: <ready|wip>
=> Small update

src/status_im/translations/ko.cljs
Updated some awkward translations and added missing entries.
I expect most of translation suits fine, but not 100% sure since Buck build is keep emitting errors on my configuration.
status: <ready|wip>
=> Korean translation: Added some missing entries & improvements

src/status_im/translations/en.cljs, src/status_im/translations/nl.cljs
fixes n/a
Added support for missing translations to Dutch.
- Know dutch
- Open Status
- Check if it's correct
status: ready
=> 🇳🇱 Update nl.cljs

src/status_im/translations/de.cljs
fixes #1313 
Tried to do it on mobile 2 hours ago and ended up accidentally deleting it...so again:
changed "formal" you to "personal" you as thought it would fit better.
changed several changes, small as well as big ones
will need to play around with the app more to be sure if i interpreted the constellation of some of those translations correctly
=> "Patch" 1.0

README.md
Fixes the broken images in README like described in #1323
=> Fix broken images in README.md (#1323)

android/app/build.gradle, android/app/src/main/AndroidManifest.xml
=> disable split screen mode on Android

src/status_im/translations/ne.cljs
noticed some typos after previous pull request was pulled.
Made a semantical correction for "left" which at first was interpreted as having to do with direction, where actually it was about "leaving".
Made a grammatical correction relating to singular plural usage.
Made comment consistent.
=> Updated ne.cljs

src/status_im/translations/ms.cljs
Translated more strings, corrected some misspelling and improved some phrase structure.
=> Update Bahasa Malaysia translation

run-osx.sh
=> Allow to run ./run-osx.sh without iterm (using standard terminal)

project.clj, src/status_im/accounts/recover/screen.cljs, src/status_im/accounts/recover/validations.cljs, src/status_im/components/drawer/view.cljs, src/status_im/components/nfc.cljs, src/status_im/contacts/validations.cljs, src/status_im/contacts/views/new_contact.cljs, src/status_im/new_group/screen_private.cljs, src/status_im/new_group/screen_public.cljs, src/status_im/new_group/validations.cljs, src/status_im/new_group/views/chat_group_settings.cljs, src/status_im/profile/edit/screen.cljs, src/status_im/profile/validations.cljs, src/status_im/protocol/chat.cljs, src/status_im/protocol/core.cljs, src/status_im/protocol/discoveries.cljs, src/status_im/protocol/group.cljs, src/status_im/protocol/message.cljs, src/status_im/protocol/validation.clj, src/status_im/protocol/web3/delivery.cljs, src/status_im/protocol/web3/filtering.cljs, src/status_im/protocol/web3/transport.cljs
=> Upgrade clojurescript to 1.9.671

src/status_im/accounts/handlers.cljs, src/status_im/accounts/specs.cljs, src/status_im/android/core.cljs, src/status_im/chat/handlers.cljs, src/status_im/chat/handlers/unviewed_messages.cljs, src/status_im/chat/specs.cljs, src/status_im/commands/handlers/loading.cljs, src/status_im/contacts/handlers.cljs, src/status_im/contacts/specs.cljs, src/status_im/db.cljs, src/status_im/discover/specs.cljs, src/status_im/discover/subs.cljs, src/status_im/group_settings/handlers.cljs, src/status_im/group_settings/subs.cljs, src/status_im/handlers.cljs, src/status_im/ios/core.cljs, src/status_im/navigation/handlers.cljs, src/status_im/navigation/specs.cljs, src/status_im/new_group/handlers.cljs, src/status_im/new_group/screen_public.cljs, src/status_im/new_group/specs.cljs, src/status_im/profile/specs.cljs, src/status_im/qr_scanner/specs.cljs, src/status_im/specs.cljs, src/status_im/transactions/specs.cljs, src/status_im/utils/db.clj, src/status_im/utils/handlers.cljs
added all fields in initial state, added comments , changed `dissoc` on `assoc nil`
status: ready
=> Feature/app-db revision and spec 

src/status_im/accounts/specs.cljs, src/status_im/chat/specs.cljs, src/status_im/discover/specs.cljs, src/status_im/specs.cljs
=> fixes specs

src/status_im/accounts/specs.cljs, src/status_im/chat/specs.cljs, src/status_im/contacts/specs.cljs, src/status_im/discover/specs.cljs, src/status_im/navigation/specs.cljs, src/status_im/new_group/specs.cljs, src/status_im/profile/specs.cljs, src/status_im/qr_scanner/specs.cljs, src/status_im/specs.cljs, src/status_im/transactions/specs.cljs
=> make all specs nilable

src/status_im/accounts/handlers.cljs
=> re-frame post migration bugs [WIP]

src/status_im/specs.cljs
Specs check was failing during synchronisation.
status: ready
=> Added missing spec for :sync-data key

src/status_im/chat/handlers.cljs
=> fix #1432 (related to re-frame migration)

src/status_im/i18n.cljs
=> fixed es-mx ns

src/status_im/chat/handlers/webview_bridge.cljs, src/status_im/chat/subs.cljs, src/status_im/chat/views/actions.cljs, src/status_im/chat/views/message/message.cljs, src/status_im/chat/views/toolbar_content.cljs, src/status_im/utils/views.clj
fix #1414
Also contains fix for view components that were subscribing on `:chat-properties` and didn't work properly after migration to new version of re-frame.
status: ready
=> fix sending/requestion ETH from Wallet dapp #1414 

src/status_im/chat/handlers/input.cljs, src/status_im/chat/models/input.cljs, src/status_im/chat/views/message/request_message.cljs
=> Bug/The second request becomes inactive if tap on the third one (#1394)

android/app/src/main/java/im/status/ethereum/MainActivity.java, ios/StatusIm.xcodeproj/project.pbxproj, ios/StatusIm/AppDelegate.m, ios/TestFairy.h, ios/upload-dsym.sh
=> testfairy integration on iOS

package.json, project.clj, src/status_im/protocol/core.cljs, src/status_im/protocol/handlers.cljs, src/status_im/protocol/web3/keys.cljs, src/status_im/protocol/web3/utils.cljs, src/status_im/utils/web3_provider.cljs, test/cljs/status_im/test/protocol/core.cljs, test/cljs/status_im/test/protocol/node.cljs, test/cljs/status_im/test/protocol/runner.cljs, test/cljs/status_im/test/protocol/utils.cljs
This PR just adds changes from https://github.com/status-im/status-react/pull/1413 on top of current `develop`. 
status: ready
=> Messaging tests 

src/status_im/protocol/handlers.cljs
=> fix missed web3 object

src/status_im/translations/af.cljs, src/status_im/translations/de.cljs, src/status_im/translations/es.cljs, src/status_im/translations/es_ar.cljs, src/status_im/translations/fr_ch.cljs, src/status_im/translations/hi.cljs, src/status_im/translations/hu.cljs, src/status_im/translations/it.cljs, src/status_im/translations/it_ch.cljs, src/status_im/translations/pl.cljs, src/status_im/translations/pt_br.cljs, src/status_im/translations/pt_pt.cljs, src/status_im/translations/ro.cljs, src/status_im/translations/ru.cljs, src/status_im/translations/sl.cljs, src/status_im/translations/sv.cljs, src/status_im/translations/th.cljs, src/status_im/translations/tr.cljs, src/status_im/translations/uk.cljs, src/status_im/translations/ur.cljs, src/status_im/translations/vi.cljs
fixes #1479
Pieces of code are shown for Debug -> On command in console when device is set to Russian language
* Set device language to Russian
* Open Status
* Go to Console
* Perform /debug -> On command
status: ready
=> Upgraded translations to reflect changes to :debug-enabled

src/status_im/chat/models/input.cljs, src/status_im/chat/views/message/request_message.cljs
=> Can use requesting message to send ether if recipient name contains double quotes (#1411)

Jenkinsfile
this PR will fix the next jenkins builds:
http://185.90.37.243:8080/job/Github%20Org%20Builder/job/status-react/job/feature%252Fupgrade-natal-shell/3/
http://185.90.37.243:8080/job/Github%20Org%20Builder/job/status-react/job/bug%252Ffee-precision-%25231489/1/
status: ready
=> fix ArgumentError - invalid byte sequence in US-ASCII at pod install

project.clj, src/status_im/utils/listview.cljs
Upgraded `natal-shell` to latest version. Reduces the number of deps transitively added.
status: ready
=> Upgraded natal-shell

README.md, android/gradle.properties
My first shy PR, no code changes :)
* A comment to provide some guidance for Android newbies when it comes to setup a keystore
* Fix Typos on Readme
status: ready
=> Fix README typos, add comment for Android keystore setup

package-lock.json
Prevent's updating of npm deps without our knowledge. Related to #1473.
status: ready
=> add package-lock.json file

src/status_im/chat/models/input.cljs, test/cljs/status_im/test/chat/models/input.cljs
=> Unit tests for input model, small updates to input methods

src/status_im/accounts/recover/handlers.cljs, src/status_im/chat/handlers/send_message.cljs, src/status_im/components/status.cljs
=> Remove sensitive data from debug output

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/im/status/ethereum/MainActivity.java
Report max memory available on current platform
=> Added alert when exception are thrown Java side.

src/status_im/android/core.cljs, src/status_im/chat/views/api/geolocation/views.cljs, src/status_im/chat/views/bottom_info.cljs, src/status_im/chat/views/input/animations/expandable.cljs, src/status_im/chat/views/input/input.cljs, src/status_im/chat/views/message/message.cljs, src/status_im/chat/views/message/request_message.cljs, src/status_im/chats_list/views/inner_item.cljs, src/status_im/components/main_tabs.cljs, src/status_im/components/sync_state/gradient.cljs, src/status_im/components/sync_state/offline.cljs, src/status_im/ios/core.cljs, src/status_im/utils/views.clj
Make sure components use :reagent-render.
To improve debug all reagent components now have a unique `display-name`. 
status: ready
=> Give all components a :display-name.

android/app/build.gradle, android/app/src/main/java/im/status/ethereum/MainActivity.java, android/app/src/main/java/im/status/ethereum/MainApplication.java, modules/react-native-status/android/build.gradle
Fixed android build configuration to have application correctly configured for older android devices.
_Steps to test_
* start application on a device running android 4.4
* application should not crash during startup
status: ready
#620
=> Fixed multidex configuration for android 4.4

src/status_im/contacts/events.cljs, src/status_im/utils/handlers.cljs, test/cljs/status_im/test/contacts/handlers.cljs
=> Feature/tests for contacts events (#1533)

src/status_im/chat/handlers.cljs, src/status_im/contacts/events.cljs, src/status_im/group/events.cljs, src/status_im/handlers.cljs, test/cljs/status_im/test/contacts/handlers.cljs
=> Feature/tests for group module (#1534)

ios/StatusIm/AppDelegate.m
=> init Instabug & fix TestFairy check [iOS]

src/status_im/android/core.cljs, src/status_im/components/main_tabs.cljs, src/status_im/components/tabs/tabs.cljs, src/status_im/ios/core.cljs, src/status_im/ui/screens/wallet/send/styles.cljs, src/status_im/ui/screens/wallet/send/views.cljs
This PR amends main wallet screen with basic navigation to a mocked send transaction screen.
status: wip but ready to merge since we don't render anywhere
=> wallet (WIP): Hook up handlers to minimal send-transaction screen

Jenkinsfile
=> deploy apk to diawi

src/status_im/ui/screens/views.cljs
=> fixed wallet screens

src/status_im/ui/screens/views.cljs
=> Feature/introduce new hierarchy fix wallet (fix)

react-native/src/status_im/react_native/js_dependencies.cljs, src/status_im/translations/en.cljs, src/status_im/ui/screens/events.cljs, src/status_im/utils/config.cljs, test/cljs/status_im/react_native/js_dependencies.cljs
=> Show testfairy warning on startup (#1569)
